import type { DiagramIR } from "@/features/llm/ir/ir.types";

/**
 * Case A (C4 insurer, ~40 nodes), run 3.
 *
 * Captured verbatim from a real model response on 2026-08-27 and frozen here.
 * Not authored, not repaired, not tidied: what the model wrote is what runs.
 * Provenance and the run's measurements are in
 * `docs/fatia1-transporte/A-run3.ir.json` and `A-run3.measure.json`.
 */
export const aRun3: DiagramIR = {
  type: "c4-container",
  nodes: [
    {
      id: "segurado",
      semanticType: "person",
      name: "Segurado",
      parentId: null,
      tier: "external",
    },
    {
      id: "corretor",
      semanticType: "person",
      name: "Corretor",
      parentId: null,
      tier: "external",
    },
    {
      id: "analista-sinistro",
      semanticType: "person",
      name: "Analista de Sinistro",
      parentId: null,
      tier: "external",
    },
    {
      id: "subscritor",
      semanticType: "person",
      name: "Subscritor",
      parentId: null,
      tier: "external",
    },
    {
      id: "seguradora",
      semanticType: "container",
      name: "Seguradora",
      parentId: null,
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "portal-corretor",
      semanticType: "container",
      name: "Portal do Corretor",
      technology: "SPA Vue.js",
      parentId: "seguradora",
      tier: "edge",
    },
    {
      id: "dominio-emissao",
      semanticType: "container",
      name: "Domínio Emissão de Apólice",
      parentId: "seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "emissao-api",
      semanticType: "container",
      name: "API Emissão",
      technology: "Spring Boot",
      parentId: "dominio-emissao",
      tier: "compute",
    },
    {
      id: "emissao-worker",
      semanticType: "container",
      name: "Worker Emissão",
      technology: "Node.js",
      parentId: "dominio-emissao",
      tier: "compute",
    },
    {
      id: "emissao-regras",
      semanticType: "container",
      name: "Serviço de Regras Emissão",
      technology: "Drools",
      parentId: "dominio-emissao",
      tier: "compute",
    },
    {
      id: "emissao-db",
      semanticType: "database",
      name: "BD Emissão de Apólice",
      technology: "PostgreSQL",
      parentId: "dominio-emissao",
      tier: "data",
    },
    {
      id: "dominio-sinistro",
      semanticType: "container",
      name: "Domínio Gestão de Sinistro",
      parentId: "seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "sinistro-api",
      semanticType: "container",
      name: "API Sinistro",
      technology: "Java Quarkus",
      parentId: "dominio-sinistro",
      tier: "compute",
    },
    {
      id: "sinistro-worker",
      semanticType: "container",
      name: "Worker Sinistro",
      technology: "Python",
      parentId: "dominio-sinistro",
      tier: "compute",
    },
    {
      id: "sinistro-regras",
      semanticType: "container",
      name: "Serviço de Regras Sinistro",
      technology: "Drools",
      parentId: "dominio-sinistro",
      tier: "compute",
    },
    {
      id: "sinistro-db",
      semanticType: "database",
      name: "BD Sinistro",
      technology: "MongoDB",
      parentId: "dominio-sinistro",
      tier: "data",
    },
    {
      id: "dominio-subscricao",
      semanticType: "container",
      name: "Domínio Subscrição",
      parentId: "seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "subscricao-api",
      semanticType: "container",
      name: "API Subscrição",
      technology: "Spring Boot",
      parentId: "dominio-subscricao",
      tier: "compute",
    },
    {
      id: "subscricao-worker",
      semanticType: "container",
      name: "Worker Subscrição",
      technology: "Python",
      parentId: "dominio-subscricao",
      tier: "compute",
    },
    {
      id: "subscricao-regras",
      semanticType: "container",
      name: "Serviço de Regras Subscrição",
      technology: "Drools",
      parentId: "dominio-subscricao",
      tier: "compute",
    },
    {
      id: "subscricao-db",
      semanticType: "database",
      name: "BD Subscrição",
      technology: "PostgreSQL",
      parentId: "dominio-subscricao",
      tier: "data",
    },
    {
      id: "dominio-pagamento",
      semanticType: "container",
      name: "Domínio Pagamento",
      parentId: "seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "pagamento-api",
      semanticType: "container",
      name: "API Pagamento",
      technology: "Java",
      parentId: "dominio-pagamento",
      tier: "compute",
    },
    {
      id: "pagamento-worker",
      semanticType: "container",
      name: "Worker Pagamento",
      technology: "Node.js",
      parentId: "dominio-pagamento",
      tier: "compute",
    },
    {
      id: "pagamento-regras",
      semanticType: "container",
      name: "Serviço de Regras Pagamento",
      technology: "Drools",
      parentId: "dominio-pagamento",
      tier: "compute",
    },
    {
      id: "pagamento-db",
      semanticType: "database",
      name: "BD Pagamento",
      technology: "PostgreSQL",
      parentId: "dominio-pagamento",
      tier: "data",
    },
    {
      id: "dominio-fraude",
      semanticType: "container",
      name: "Domínio Detecção de Fraude",
      parentId: "seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "fraude-api",
      semanticType: "container",
      name: "API Fraude",
      technology: "Python",
      parentId: "dominio-fraude",
      tier: "compute",
    },
    {
      id: "fraude-worker",
      semanticType: "container",
      name: "Worker Fraude",
      technology: "Go",
      parentId: "dominio-fraude",
      tier: "compute",
    },
    {
      id: "fraude-regras",
      semanticType: "container",
      name: "Serviço de Regras Fraude",
      technology: "Drools",
      parentId: "dominio-fraude",
      tier: "compute",
    },
    {
      id: "fraude-db",
      semanticType: "database",
      name: "BD Fraude",
      technology: "MongoDB",
      parentId: "dominio-fraude",
      tier: "data",
    },
    {
      id: "dominio-integration",
      semanticType: "container",
      name: "Camada de Integração",
      parentId: "seguradora",
      isBoundary: true,
      tier: "integration",
    },
    {
      id: "mensageria",
      semanticType: "container",
      name: "Fila de Mensageria",
      technology: "RabbitMQ",
      parentId: "dominio-integration",
      tier: "integration",
    },
    {
      id: "eventbus",
      semanticType: "container",
      name: "Barramento de Eventos",
      technology: "Kafka",
      parentId: "dominio-integration",
      tier: "integration",
    },
  ],
  edges: [
    {
      id: "segurado-portal",
      sourceId: "segurado",
      targetId: "portal-corretor",
      label: "acessa",
    },
    {
      id: "corretor-portal",
      sourceId: "corretor",
      targetId: "portal-corretor",
      label: "acessa",
    },
    {
      id: "portal-emissao",
      sourceId: "portal-corretor",
      targetId: "emissao-api",
      label: "solicita cotação/emissão",
    },
    {
      id: "emissao-api-worker",
      sourceId: "emissao-api",
      targetId: "emissao-worker",
      label: "envia tarefas",
    },
    {
      id: "emissao-api-regras",
      sourceId: "emissao-api",
      targetId: "emissao-regras",
      label: "consulta regras",
    },
    {
      id: "emissao-api-db",
      sourceId: "emissao-api",
      targetId: "emissao-db",
      label: "CRUD apólices",
    },
    {
      id: "emissao-worker-db",
      sourceId: "emissao-worker",
      targetId: "emissao-db",
      label: "atualiza/consulta",
    },
    {
      id: "emissao-worker-regras",
      sourceId: "emissao-worker",
      targetId: "emissao-regras",
      label: "consulta regras",
    },
    {
      id: "portal-sinistro",
      sourceId: "portal-corretor",
      targetId: "sinistro-api",
      label: "abre sinistro",
    },
    {
      id: "analista-sinistro-app",
      sourceId: "analista-sinistro",
      targetId: "sinistro-api",
      label: "consulta/processa",
    },
    {
      id: "sinistro-api-worker",
      sourceId: "sinistro-api",
      targetId: "sinistro-worker",
      label: "envia tarefas",
    },
    {
      id: "sinistro-api-regras",
      sourceId: "sinistro-api",
      targetId: "sinistro-regras",
      label: "consulta regras",
    },
    {
      id: "sinistro-api-db",
      sourceId: "sinistro-api",
      targetId: "sinistro-db",
      label: "CRUD sinistros",
    },
    {
      id: "sinistro-worker-db",
      sourceId: "sinistro-worker",
      targetId: "sinistro-db",
      label: "atualiza consulta",
    },
    {
      id: "sinistro-worker-regras",
      sourceId: "sinistro-worker",
      targetId: "sinistro-regras",
      label: "consulta regras",
    },
    {
      id: "portal-subscricao",
      sourceId: "portal-corretor",
      targetId: "subscricao-api",
      label: "solicita subscrição",
    },
    {
      id: "subscritor-app",
      sourceId: "subscritor",
      targetId: "subscricao-api",
      label: "analisa propostas",
    },
    {
      id: "subscricao-api-worker",
      sourceId: "subscricao-api",
      targetId: "subscricao-worker",
      label: "envia tarefas",
    },
    {
      id: "subscricao-api-regras",
      sourceId: "subscricao-api",
      targetId: "subscricao-regras",
      label: "consulta regras",
    },
    {
      id: "subscricao-api-db",
      sourceId: "subscricao-api",
      targetId: "subscricao-db",
      label: "CRUD subscrições",
    },
    {
      id: "subscricao-worker-db",
      sourceId: "subscricao-worker",
      targetId: "subscricao-db",
      label: "atualiza consulta",
    },
    {
      id: "subscricao-worker-regras",
      sourceId: "subscricao-worker",
      targetId: "subscricao-regras",
      label: "consulta regras",
    },
    {
      id: "portal-pagamento",
      sourceId: "portal-corretor",
      targetId: "pagamento-api",
      label: "solicita pagamento",
    },
    {
      id: "pagamento-api-worker",
      sourceId: "pagamento-api",
      targetId: "pagamento-worker",
      label: "envia tarefas",
    },
    {
      id: "pagamento-api-regras",
      sourceId: "pagamento-api",
      targetId: "pagamento-regras",
      label: "consulta regras",
    },
    {
      id: "pagamento-api-db",
      sourceId: "pagamento-api",
      targetId: "pagamento-db",
      label: "CRUD pagamentos",
    },
    {
      id: "pagamento-worker-db",
      sourceId: "pagamento-worker",
      targetId: "pagamento-db",
      label: "atualiza consulta",
    },
    {
      id: "pagamento-worker-regras",
      sourceId: "pagamento-worker",
      targetId: "pagamento-regras",
      label: "consulta regras",
    },
    {
      id: "portal-fraude",
      sourceId: "portal-corretor",
      targetId: "fraude-api",
      label: "avalia fraude no cadastro sinistro",
    },
    {
      id: "fraude-api-worker",
      sourceId: "fraude-api",
      targetId: "fraude-worker",
      label: "envia tarefas",
    },
    {
      id: "fraude-api-regras",
      sourceId: "fraude-api",
      targetId: "fraude-regras",
      label: "consulta regras",
    },
    {
      id: "fraude-api-db",
      sourceId: "fraude-api",
      targetId: "fraude-db",
      label: "CRUD casos fraude",
    },
    {
      id: "fraude-worker-db",
      sourceId: "fraude-worker",
      targetId: "fraude-db",
      label: "atualiza consulta",
    },
    {
      id: "fraude-worker-regras",
      sourceId: "fraude-worker",
      targetId: "fraude-regras",
      label: "consulta regras",
    },
    {
      id: "emissao-api-eventbus",
      sourceId: "emissao-api",
      targetId: "eventbus",
      label: "publica eventos",
    },
    {
      id: "sinistro-api-eventbus",
      sourceId: "sinistro-api",
      targetId: "eventbus",
      label: "publica eventos",
    },
    {
      id: "subscricao-api-eventbus",
      sourceId: "subscricao-api",
      targetId: "eventbus",
      label: "publica eventos",
    },
    {
      id: "pagamento-api-eventbus",
      sourceId: "pagamento-api",
      targetId: "eventbus",
      label: "publica eventos",
    },
    {
      id: "eventbus-sinistro-worker",
      sourceId: "eventbus",
      targetId: "sinistro-worker",
      label: "notifica eventos",
    },
    {
      id: "eventbus-fraude-worker",
      sourceId: "eventbus",
      targetId: "fraude-worker",
      label: "notifica eventos",
    },
  ],
};
