import type { DiagramIR } from "@/features/llm/ir/ir.types";

/**
 * Case A (C4 insurer, ~40 nodes), run 1.
 *
 * Captured verbatim from a real model response on 2026-08-27 and frozen here.
 * Not authored, not repaired, not tidied: what the model wrote is what runs.
 * Provenance and the run's measurements are in
 * `docs/fatia1-transporte/A-run1.ir.json` and `A-run1.measure.json`.
 */
export const aRun1: DiagramIR = {
  type: "c4-container",
  nodes: [
    {
      id: "segurado",
      semanticType: "person",
      name: "Segurado",
      parentId: null,
      tier: "external",
    },
    {
      id: "corretor",
      semanticType: "person",
      name: "Corretor",
      parentId: null,
      tier: "external",
    },
    {
      id: "analista-sinistro",
      semanticType: "person",
      name: "Analista de Sinistro",
      parentId: null,
      tier: "external",
    },
    {
      id: "subscritor",
      semanticType: "person",
      name: "Subscritor",
      parentId: null,
      tier: "external",
    },
    {
      id: "seguradora",
      semanticType: "container",
      name: "Plataforma Seguradora",
      parentId: null,
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "portal-corretor",
      semanticType: "container",
      name: "Portal do Corretor",
      technology: "React",
      parentId: "seguradora",
      tier: "edge",
    },
    {
      id: "api-portal-corretor",
      semanticType: "container",
      name: "API Portal do Corretor",
      technology: "Node.js",
      parentId: "seguradora",
      tier: "compute",
    },
    {
      id: "db-portal-corretor",
      semanticType: "database",
      name: "Banco Portal do Corretor",
      technology: "PostgreSQL",
      parentId: "seguradora",
      tier: "data",
    },
    {
      id: "dominio-emissao",
      semanticType: "container",
      name: "Domínio de Emissão de Apólice",
      parentId: "seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "api-emissao",
      semanticType: "container",
      name: "API Emissão",
      technology: "Java Spring Boot",
      parentId: "dominio-emissao",
      tier: "compute",
    },
    {
      id: "worker-emissao",
      semanticType: "container",
      name: "Worker Emissão",
      technology: "Python",
      parentId: "dominio-emissao",
      tier: "compute",
    },
    {
      id: "servico-regras-emissao",
      semanticType: "container",
      name: "Serviço de Regras Emissão",
      technology: "Drools",
      parentId: "dominio-emissao",
      tier: "compute",
    },
    {
      id: "db-emissao",
      semanticType: "database",
      name: "DB Emissão",
      technology: "PostgreSQL",
      parentId: "dominio-emissao",
      tier: "data",
    },
    {
      id: "dominio-sinistro",
      semanticType: "container",
      name: "Domínio Gestão de Sinistro",
      parentId: "seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "api-sinistro",
      semanticType: "container",
      name: "API Sinistro",
      technology: "Java Spring Boot",
      parentId: "dominio-sinistro",
      tier: "compute",
    },
    {
      id: "worker-sinistro",
      semanticType: "container",
      name: "Worker Sinistro",
      technology: "Python",
      parentId: "dominio-sinistro",
      tier: "compute",
    },
    {
      id: "servico-regras-sinistro",
      semanticType: "container",
      name: "Serviço de Regras Sinistro",
      technology: "Drools",
      parentId: "dominio-sinistro",
      tier: "compute",
    },
    {
      id: "db-sinistro",
      semanticType: "database",
      name: "DB Sinistro",
      technology: "PostgreSQL",
      parentId: "dominio-sinistro",
      tier: "data",
    },
    {
      id: "dominio-subscricao",
      semanticType: "container",
      name: "Domínio Subscrição",
      parentId: "seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "api-subscricao",
      semanticType: "container",
      name: "API Subscrição",
      technology: "Java Spring Boot",
      parentId: "dominio-subscricao",
      tier: "compute",
    },
    {
      id: "worker-subscricao",
      semanticType: "container",
      name: "Worker Subscrição",
      technology: "Python",
      parentId: "dominio-subscricao",
      tier: "compute",
    },
    {
      id: "servico-regras-subscricao",
      semanticType: "container",
      name: "Serviço de Regras Subscrição",
      technology: "Drools",
      parentId: "dominio-subscricao",
      tier: "compute",
    },
    {
      id: "db-subscricao",
      semanticType: "database",
      name: "DB Subscrição",
      technology: "PostgreSQL",
      parentId: "dominio-subscricao",
      tier: "data",
    },
    {
      id: "dominio-pagamento",
      semanticType: "container",
      name: "Domínio Pagamento",
      parentId: "seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "api-pagamento",
      semanticType: "container",
      name: "API Pagamento",
      technology: "Java Spring Boot",
      parentId: "dominio-pagamento",
      tier: "compute",
    },
    {
      id: "worker-pagamento",
      semanticType: "container",
      name: "Worker Pagamento",
      technology: "Python",
      parentId: "dominio-pagamento",
      tier: "compute",
    },
    {
      id: "servico-regras-pagamento",
      semanticType: "container",
      name: "Serviço de Regras Pagamento",
      technology: "Drools",
      parentId: "dominio-pagamento",
      tier: "compute",
    },
    {
      id: "db-pagamento",
      semanticType: "database",
      name: "DB Pagamento",
      technology: "PostgreSQL",
      parentId: "dominio-pagamento",
      tier: "data",
    },
    {
      id: "dominio-fraude",
      semanticType: "container",
      name: "Domínio Detecção de Fraude",
      parentId: "seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "api-fraude",
      semanticType: "container",
      name: "API Fraude",
      technology: "Java Spring Boot",
      parentId: "dominio-fraude",
      tier: "compute",
    },
    {
      id: "worker-fraude",
      semanticType: "container",
      name: "Worker Fraude",
      technology: "Python",
      parentId: "dominio-fraude",
      tier: "compute",
    },
    {
      id: "servico-regras-fraude",
      semanticType: "container",
      name: "Serviço de Regras Fraude",
      technology: "Drools",
      parentId: "dominio-fraude",
      tier: "compute",
    },
    {
      id: "db-fraude",
      semanticType: "database",
      name: "DB Fraude",
      technology: "PostgreSQL",
      parentId: "dominio-fraude",
      tier: "data",
    },
  ],
  edges: [
    {
      id: "portal-corretor-to-api",
      sourceId: "portal-corretor",
      targetId: "api-portal-corretor",
      label: "requisições HTTP",
    },
    {
      id: "segurado-to-portal",
      sourceId: "segurado",
      targetId: "portal-corretor",
      label: "consulta apólice",
    },
    {
      id: "corretor-to-portal",
      sourceId: "corretor",
      targetId: "portal-corretor",
      label: "emissão e acompanhamento",
    },
    {
      id: "portal-api-emissao",
      sourceId: "api-portal-corretor",
      targetId: "api-emissao",
      label: "emite apólice",
    },
    {
      id: "portal-api-sinistro",
      sourceId: "api-portal-corretor",
      targetId: "api-sinistro",
      label: "notifica sinistro",
    },
    {
      id: "portal-api-subscricao",
      sourceId: "api-portal-corretor",
      targetId: "api-subscricao",
      label: "cotação/subscrição",
    },
    {
      id: "portal-api-pagamento",
      sourceId: "api-portal-corretor",
      targetId: "api-pagamento",
      label: "consulta pagamentos",
    },
    {
      id: "portal-db",
      sourceId: "api-portal-corretor",
      targetId: "db-portal-corretor",
      label: "acessa dados",
    },
    {
      id: "api-emissao-to-db",
      sourceId: "api-emissao",
      targetId: "db-emissao",
      label: "CRUD apólices",
    },
    {
      id: "api-emissao-to-worker",
      sourceId: "api-emissao",
      targetId: "worker-emissao",
      label: "processa emissão",
    },
    {
      id: "worker-emissao-to-regras",
      sourceId: "worker-emissao",
      targetId: "servico-regras-emissao",
      label: "consulta regras",
    },
    {
      id: "worker-emissao-to-db",
      sourceId: "worker-emissao",
      targetId: "db-emissao",
      label: "atualiza status",
    },
    {
      id: "api-sinistro-to-db",
      sourceId: "api-sinistro",
      targetId: "db-sinistro",
      label: "CRUD sinistro",
    },
    {
      id: "api-sinistro-to-worker",
      sourceId: "api-sinistro",
      targetId: "worker-sinistro",
      label: "enfileira eventos",
    },
    {
      id: "worker-sinistro-to-regras",
      sourceId: "worker-sinistro",
      targetId: "servico-regras-sinistro",
      label: "validação de elegibilidade",
    },
    {
      id: "worker-sinistro-to-db",
      sourceId: "worker-sinistro",
      targetId: "db-sinistro",
      label: "atualiza sinistro",
    },
    {
      id: "api-subscricao-to-db",
      sourceId: "api-subscricao",
      targetId: "db-subscricao",
      label: "CRUD avaliação",
    },
    {
      id: "api-subscricao-to-worker",
      sourceId: "api-subscricao",
      targetId: "worker-subscricao",
      label: "enfileira tarefas",
    },
    {
      id: "worker-subscricao-to-regras",
      sourceId: "worker-subscricao",
      targetId: "servico-regras-subscricao",
      label: "consulta limites e perfis",
    },
    {
      id: "worker-subscricao-to-db",
      sourceId: "worker-subscricao",
      targetId: "db-subscricao",
      label: "atualiza decisão",
    },
    {
      id: "api-pagamento-to-db",
      sourceId: "api-pagamento",
      targetId: "db-pagamento",
      label: "CRUD pagamentos",
    },
    {
      id: "api-pagamento-to-worker",
      sourceId: "api-pagamento",
      targetId: "worker-pagamento",
      label: "geração de boletos",
    },
    {
      id: "worker-pagamento-to-regras",
      sourceId: "worker-pagamento",
      targetId: "servico-regras-pagamento",
      label: "verifica regras de cobrança",
    },
    {
      id: "worker-pagamento-to-db",
      sourceId: "worker-pagamento",
      targetId: "db-pagamento",
      label: "atualiza status pagamento",
    },
    {
      id: "api-fraude-to-db",
      sourceId: "api-fraude",
      targetId: "db-fraude",
      label: "CRUD indicadores",
    },
    {
      id: "api-fraude-to-worker",
      sourceId: "api-fraude",
      targetId: "worker-fraude",
      label: "detecção em batch",
    },
    {
      id: "worker-fraude-to-regras",
      sourceId: "worker-fraude",
      targetId: "servico-regras-fraude",
      label: "aplica validações",
    },
    {
      id: "worker-fraude-to-db",
      sourceId: "worker-fraude",
      targetId: "db-fraude",
      label: "grava detecções",
    },
    {
      id: "analista-sinistro-to-api-sinistro",
      sourceId: "analista-sinistro",
      targetId: "api-sinistro",
      label: "analisa e acompanha sinistro",
    },
    {
      id: "subscritor-to-api-subscricao",
      sourceId: "subscritor",
      targetId: "api-subscricao",
      label: "aprova/rejeita cotação",
    },
    {
      id: "dominio-fraude-to-sinistro",
      sourceId: "servico-regras-fraude",
      targetId: "api-sinistro",
      label: "notifica possíveis fraudes",
    },
    {
      id: "dominio-fraude-to-emissao",
      sourceId: "servico-regras-fraude",
      targetId: "api-emissao",
      label: "verifica fraude antes da emissão",
    },
    {
      id: "sinistro-to-pagamento",
      sourceId: "api-sinistro",
      targetId: "api-pagamento",
      label: "autoriza/nega pagamentos de indenização",
    },
  ],
};
