import type { DiagramIR } from "@/features/llm/ir/ir.types";

/**
 * Case A (C4 insurer, ~40 nodes), run 2.
 *
 * Captured verbatim from a real model response on 2026-08-27 and frozen here.
 * Not authored, not repaired, not tidied: what the model wrote is what runs.
 * Provenance and the run's measurements are in
 * `docs/fatia1-transporte/A-run2.ir.json` and `A-run2.measure.json`.
 */
export const aRun2: DiagramIR = {
  type: "c4-container",
  nodes: [
    {
      id: "segurado",
      semanticType: "person",
      name: "Segurado",
      parentId: null,
      tier: "external",
    },
    {
      id: "corretor",
      semanticType: "person",
      name: "Corretor",
      parentId: null,
      tier: "external",
    },
    {
      id: "analista-sinistro",
      semanticType: "person",
      name: "Analista de Sinistro",
      parentId: null,
      tier: "external",
    },
    {
      id: "subscritor",
      semanticType: "person",
      name: "Subscritor",
      parentId: null,
      tier: "external",
    },
    {
      id: "sistema-seguradora",
      semanticType: "container",
      name: "Sistema Seguradora",
      parentId: null,
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "api-portal-corretor",
      semanticType: "container",
      name: "API Portal do Corretor",
      technology: "Node.js",
      parentId: "sistema-seguradora",
      tier: "edge",
    },
    {
      id: "web-portal-corretor",
      semanticType: "container",
      name: "Portal do Corretor (Web)",
      technology: "React",
      parentId: "sistema-seguradora",
      tier: "edge",
    },
    {
      id: "db-portal-corretor",
      semanticType: "database",
      name: "DB Portal do Corretor",
      technology: "PostgreSQL",
      parentId: "sistema-seguradora",
      tier: "data",
    },
    {
      id: "dominio-emissao",
      semanticType: "container",
      name: "Domínio Emissão de Apólice",
      parentId: "sistema-seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "api-emissao",
      semanticType: "container",
      name: "API Emissão",
      technology: "Spring Boot",
      parentId: "dominio-emissao",
      tier: "compute",
    },
    {
      id: "worker-emissao",
      semanticType: "container",
      name: "Worker Emissão",
      technology: "Celery/Python",
      parentId: "dominio-emissao",
      tier: "compute",
    },
    {
      id: "regras-emissao",
      semanticType: "container",
      name: "Serviço de Regras Emissão",
      technology: "Drools",
      parentId: "dominio-emissao",
      tier: "compute",
    },
    {
      id: "db-emissao",
      semanticType: "database",
      name: "DB Emissão",
      technology: "PostgreSQL",
      parentId: "dominio-emissao",
      tier: "data",
    },
    {
      id: "dominio-sinistro",
      semanticType: "container",
      name: "Domínio Gestão de Sinistro",
      parentId: "sistema-seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "api-sinistro",
      semanticType: "container",
      name: "API Sinistro",
      technology: "Spring Boot",
      parentId: "dominio-sinistro",
      tier: "compute",
    },
    {
      id: "worker-sinistro",
      semanticType: "container",
      name: "Worker Sinistro",
      technology: "Celery/Python",
      parentId: "dominio-sinistro",
      tier: "compute",
    },
    {
      id: "regras-sinistro",
      semanticType: "container",
      name: "Serviço de Regras Sinistro",
      technology: "Drools",
      parentId: "dominio-sinistro",
      tier: "compute",
    },
    {
      id: "db-sinistro",
      semanticType: "database",
      name: "DB Sinistro",
      technology: "MongoDB",
      parentId: "dominio-sinistro",
      tier: "data",
    },
    {
      id: "dominio-subscricao",
      semanticType: "container",
      name: "Domínio Subscrição",
      parentId: "sistema-seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "api-subscricao",
      semanticType: "container",
      name: "API Subscrição",
      technology: "Spring Boot",
      parentId: "dominio-subscricao",
      tier: "compute",
    },
    {
      id: "worker-subscricao",
      semanticType: "container",
      name: "Worker Subscrição",
      technology: "Celery/Python",
      parentId: "dominio-subscricao",
      tier: "compute",
    },
    {
      id: "regras-subscricao",
      semanticType: "container",
      name: "Serviço de Regras Subscrição",
      technology: "Drools",
      parentId: "dominio-subscricao",
      tier: "compute",
    },
    {
      id: "db-subscricao",
      semanticType: "database",
      name: "DB Subscrição",
      technology: "PostgreSQL",
      parentId: "dominio-subscricao",
      tier: "data",
    },
    {
      id: "dominio-pagamento",
      semanticType: "container",
      name: "Domínio Pagamento",
      parentId: "sistema-seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "api-pagamento",
      semanticType: "container",
      name: "API Pagamento",
      technology: "Spring Boot",
      parentId: "dominio-pagamento",
      tier: "compute",
    },
    {
      id: "worker-pagamento",
      semanticType: "container",
      name: "Worker Pagamento",
      technology: "Celery/Python",
      parentId: "dominio-pagamento",
      tier: "compute",
    },
    {
      id: "regras-pagamento",
      semanticType: "container",
      name: "Serviço de Regras Pagamento",
      technology: "Drools",
      parentId: "dominio-pagamento",
      tier: "compute",
    },
    {
      id: "db-pagamento",
      semanticType: "database",
      name: "DB Pagamento",
      technology: "MySQL",
      parentId: "dominio-pagamento",
      tier: "data",
    },
    {
      id: "dominio-fraude",
      semanticType: "container",
      name: "Domínio Detecção de Fraude",
      parentId: "sistema-seguradora",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "api-fraude",
      semanticType: "container",
      name: "API Fraude",
      technology: "Spring Boot",
      parentId: "dominio-fraude",
      tier: "compute",
    },
    {
      id: "worker-fraude",
      semanticType: "container",
      name: "Worker Fraude",
      technology: "Celery/Python",
      parentId: "dominio-fraude",
      tier: "compute",
    },
    {
      id: "regras-fraude",
      semanticType: "container",
      name: "Serviço de Regras Fraude",
      technology: "Drools",
      parentId: "dominio-fraude",
      tier: "compute",
    },
    {
      id: "db-fraude",
      semanticType: "database",
      name: "DB Fraude",
      technology: "MongoDB",
      parentId: "dominio-fraude",
      tier: "data",
    },
    {
      id: "db-central-relatorios",
      semanticType: "database",
      name: "DB Central de Relatórios",
      technology: "Data Warehouse",
      parentId: "sistema-seguradora",
      tier: "data",
    },
  ],
  edges: [
    {
      id: "segurado-para-portal",
      sourceId: "segurado",
      targetId: "web-portal-corretor",
      label: "acessa",
    },
    {
      id: "corretor-para-portal",
      sourceId: "corretor",
      targetId: "web-portal-corretor",
      label: "acessa",
    },
    {
      id: "web-portal-para-api-portal",
      sourceId: "web-portal-corretor",
      targetId: "api-portal-corretor",
      label: "HTTPS",
    },
    {
      id: "api-portal-para-db-portal",
      sourceId: "api-portal-corretor",
      targetId: "db-portal-corretor",
      label: "CRUD",
    },
    {
      id: "api-portal-para-api-emissao",
      sourceId: "api-portal-corretor",
      targetId: "api-emissao",
      label: "solicita emissão",
    },
    {
      id: "api-portal-para-api-sinistro",
      sourceId: "api-portal-corretor",
      targetId: "api-sinistro",
      label: "abre sinistro",
    },
    {
      id: "api-portal-para-api-subscricao",
      sourceId: "api-portal-corretor",
      targetId: "api-subscricao",
      label: "envia proposta",
    },
    {
      id: "api-portal-para-api-pagamento",
      sourceId: "api-portal-corretor",
      targetId: "api-pagamento",
      label: "realiza pagamento",
    },
    {
      id: "api-emissao-para-db-emissao",
      sourceId: "api-emissao",
      targetId: "db-emissao",
      label: "CRUD apólices",
    },
    {
      id: "api-emissao-para-worker-emissao",
      sourceId: "api-emissao",
      targetId: "worker-emissao",
      label: "envia tarefas de emissão",
    },
    {
      id: "api-emissao-para-regras-emissao",
      sourceId: "api-emissao",
      targetId: "regras-emissao",
      label: "consulta regras",
    },
    {
      id: "worker-emissao-para-db-emissao",
      sourceId: "worker-emissao",
      targetId: "db-emissao",
      label: "atualiza status",
    },
    {
      id: "worker-emissao-para-regras-emissao",
      sourceId: "worker-emissao",
      targetId: "regras-emissao",
      label: "avalia regras",
    },
    {
      id: "api-sinistro-para-db-sinistro",
      sourceId: "api-sinistro",
      targetId: "db-sinistro",
      label: "CRUD sinistros",
    },
    {
      id: "api-sinistro-para-worker-sinistro",
      sourceId: "api-sinistro",
      targetId: "worker-sinistro",
      label: "processa eventos",
    },
    {
      id: "api-sinistro-para-regras-sinistro",
      sourceId: "api-sinistro",
      targetId: "regras-sinistro",
      label: "consulta regras",
    },
    {
      id: "worker-sinistro-para-db-sinistro",
      sourceId: "worker-sinistro",
      targetId: "db-sinistro",
      label: "atualiza eventos",
    },
    {
      id: "worker-sinistro-para-regras-sinistro",
      sourceId: "worker-sinistro",
      targetId: "regras-sinistro",
      label: "avalia regras",
    },
    {
      id: "analista-sinistro-para-api-sinistro",
      sourceId: "analista-sinistro",
      targetId: "api-sinistro",
      label: "analisa sinistro",
    },
    {
      id: "api-subscricao-para-db-subscricao",
      sourceId: "api-subscricao",
      targetId: "db-subscricao",
      label: "CRUD propostas",
    },
    {
      id: "api-subscricao-para-worker-subscricao",
      sourceId: "api-subscricao",
      targetId: "worker-subscricao",
      label: "valida subscrição",
    },
    {
      id: "api-subscricao-para-regras-subscricao",
      sourceId: "api-subscricao",
      targetId: "regras-subscricao",
      label: "consulta regras",
    },
    {
      id: "worker-subscricao-para-db-subscricao",
      sourceId: "worker-subscricao",
      targetId: "db-subscricao",
      label: "atualiza status",
    },
    {
      id: "worker-subscricao-para-regras-subscricao",
      sourceId: "worker-subscricao",
      targetId: "regras-subscricao",
      label: "avalia regras",
    },
    {
      id: "subscritor-para-api-subscricao",
      sourceId: "subscritor",
      targetId: "api-subscricao",
      label: "aprova proposta",
    },
    {
      id: "api-pagamento-para-db-pagamento",
      sourceId: "api-pagamento",
      targetId: "db-pagamento",
      label: "CRUD pagamentos",
    },
    {
      id: "api-pagamento-para-worker-pagamento",
      sourceId: "api-pagamento",
      targetId: "worker-pagamento",
      label: "processa pagamentos",
    },
    {
      id: "api-pagamento-para-regras-pagamento",
      sourceId: "api-pagamento",
      targetId: "regras-pagamento",
      label: "consulta regras",
    },
    {
      id: "worker-pagamento-para-db-pagamento",
      sourceId: "worker-pagamento",
      targetId: "db-pagamento",
      label: "atualiza transações",
    },
    {
      id: "worker-pagamento-para-regras-pagamento",
      sourceId: "worker-pagamento",
      targetId: "regras-pagamento",
      label: "avalia regras",
    },
    {
      id: "api-fraude-para-db-fraude",
      sourceId: "api-fraude",
      targetId: "db-fraude",
      label: "armazenamento",
    },
    {
      id: "api-fraude-para-worker-fraude",
      sourceId: "api-fraude",
      targetId: "worker-fraude",
      label: "processamento",
    },
    {
      id: "api-fraude-para-regras-fraude",
      sourceId: "api-fraude",
      targetId: "regras-fraude",
      label: "consulta regras",
    },
    {
      id: "worker-fraude-para-db-fraude",
      sourceId: "worker-fraude",
      targetId: "db-fraude",
      label: "armazena eventos",
    },
    {
      id: "worker-fraude-para-regras-fraude",
      sourceId: "worker-fraude",
      targetId: "regras-fraude",
      label: "valida padrões",
    },
    {
      id: "db-emissao-para-db-central",
      sourceId: "db-emissao",
      targetId: "db-central-relatorios",
      label: "extrai dados",
    },
    {
      id: "db-sinistro-para-db-central",
      sourceId: "db-sinistro",
      targetId: "db-central-relatorios",
      label: "extrai dados",
    },
    {
      id: "db-subscricao-para-db-central",
      sourceId: "db-subscricao",
      targetId: "db-central-relatorios",
      label: "extrai dados",
    },
    {
      id: "db-pagamento-para-db-central",
      sourceId: "db-pagamento",
      targetId: "db-central-relatorios",
      label: "extrai dados",
    },
    {
      id: "db-fraude-para-db-central",
      sourceId: "db-fraude",
      targetId: "db-central-relatorios",
      label: "extrai dados",
    },
  ],
};
