import type { DiagramIR } from "@/features/llm/ir/ir.types";

/**
 * Case B (AWS deployment, ~40 nodes), run 3.
 *
 * Captured verbatim from a real model response on 2026-08-27 and frozen here.
 * Not authored, not repaired, not tidied: what the model wrote is what runs.
 * Provenance and the run's measurements are in
 * `docs/fatia1-transporte/B-run3.ir.json` and `B-run3.measure.json`.
 */
export const bRun3: DiagramIR = {
  type: "aws-deployment",
  nodes: [
    {
      id: "vpc-producao",
      semanticType: "aws-vpc",
      name: "VPC Produção",
      awsService: "vpc",
      parentId: null,
      isBoundary: true,
      tier: "edge",
    },
    {
      id: "az-1",
      semanticType: "aws-az",
      name: "us-east-1a",
      parentId: "vpc-producao",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "az-2",
      semanticType: "aws-az",
      name: "us-east-1b",
      parentId: "vpc-producao",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "public-subnet-1",
      semanticType: "aws-public-subnet",
      name: "Subnet Pública 1",
      awsService: "public-subnet",
      parentId: "az-1",
      isBoundary: true,
      tier: "edge",
    },
    {
      id: "public-subnet-2",
      semanticType: "aws-public-subnet",
      name: "Subnet Pública 2",
      awsService: "public-subnet",
      parentId: "az-2",
      isBoundary: true,
      tier: "edge",
    },
    {
      id: "private-subnet-1",
      semanticType: "aws-private-subnet",
      name: "Subnet Privada 1",
      awsService: "private-subnet",
      parentId: "az-1",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "private-subnet-2",
      semanticType: "aws-private-subnet",
      name: "Subnet Privada 2",
      awsService: "private-subnet",
      parentId: "az-2",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "route-53",
      semanticType: "aws-networking",
      name: "Route 53",
      awsService: "route53",
      parentId: null,
      tier: "edge",
    },
    {
      id: "cloudfront-cdn",
      semanticType: "aws-networking",
      name: "CloudFront CDN",
      awsService: "cloudfront",
      parentId: null,
      tier: "edge",
    },
    {
      id: "alb-1",
      semanticType: "aws-networking",
      name: "ALB Público 1",
      awsService: "elb",
      parentId: "public-subnet-1",
      tier: "edge",
    },
    {
      id: "alb-2",
      semanticType: "aws-networking",
      name: "ALB Público 2",
      awsService: "elb",
      parentId: "public-subnet-2",
      tier: "edge",
    },
    {
      id: "nat-1",
      semanticType: "aws-networking",
      name: "NAT Gateway 1",
      awsService: "vpc",
      parentId: "public-subnet-1",
      tier: "ingress",
    },
    {
      id: "nat-2",
      semanticType: "aws-networking",
      name: "NAT Gateway 2",
      awsService: "vpc",
      parentId: "public-subnet-2",
      tier: "ingress",
    },
    {
      id: "ecs-cluster-1",
      semanticType: "aws-containers",
      name: "ECS Cluster 1",
      awsService: "ecs-2",
      parentId: "private-subnet-1",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "ecs-cluster-2",
      semanticType: "aws-containers",
      name: "ECS Cluster 2",
      awsService: "ecs-2",
      parentId: "private-subnet-2",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "fargate-service-1",
      semanticType: "aws-compute",
      name: "Serviço Fargate 1",
      awsService: "fargate",
      parentId: "ecs-cluster-1",
      tier: "compute",
    },
    {
      id: "fargate-service-2",
      semanticType: "aws-compute",
      name: "Serviço Fargate 2",
      awsService: "fargate",
      parentId: "ecs-cluster-2",
      tier: "compute",
    },
    {
      id: "lambda-func-app",
      semanticType: "aws-compute",
      name: "Lambda App 1",
      awsService: "lambda",
      parentId: "private-subnet-1",
      tier: "compute",
    },
    {
      id: "lambda-func-app2",
      semanticType: "aws-compute",
      name: "Lambda App 2",
      awsService: "lambda",
      parentId: "private-subnet-2",
      tier: "compute",
    },
    {
      id: "lambda-func-bg",
      semanticType: "aws-compute",
      name: "Lambda Background",
      awsService: "lambda",
      parentId: "private-subnet-1",
      tier: "compute",
    },
    {
      id: "rds-multi-az",
      semanticType: "aws-database",
      name: "RDS Multi-AZ",
      awsService: "rds",
      parentId: "vpc-producao",
      tier: "data",
    },
    {
      id: "rds-replica",
      semanticType: "aws-database",
      name: "RDS Réplica",
      awsService: "rds",
      parentId: "vpc-producao",
      tier: "data",
    },
    {
      id: "s3-bucket-app",
      semanticType: "aws-storage",
      name: "Bucket S3 App",
      awsService: "s3",
      parentId: "vpc-producao",
      tier: "data",
    },
    {
      id: "s3-bucket-static",
      semanticType: "aws-storage",
      name: "Bucket S3 Estático",
      awsService: "s3",
      parentId: "vpc-producao",
      tier: "data",
    },
    {
      id: "s3-bucket-logs",
      semanticType: "aws-storage",
      name: "Bucket S3 Logs",
      awsService: "s3",
      parentId: "vpc-producao",
      tier: "data",
    },
    {
      id: "sqs-fila-entrada",
      semanticType: "aws-integration",
      name: "SQS Fila Entrada",
      awsService: "sqs",
      parentId: "vpc-producao",
      tier: "integration",
    },
    {
      id: "sqs-fila-processo",
      semanticType: "aws-integration",
      name: "SQS Fila Processamento",
      awsService: "sqs",
      parentId: "vpc-producao",
      tier: "integration",
    },
    {
      id: "sns-topico-app",
      semanticType: "aws-integration",
      name: "SNS Tópico App",
      awsService: "sns",
      parentId: "vpc-producao",
      tier: "integration",
    },
    {
      id: "sns-topico-eventos",
      semanticType: "aws-integration",
      name: "SNS Tópico Eventos",
      awsService: "sns",
      parentId: "vpc-producao",
      tier: "integration",
    },
    {
      id: "secrets-manager",
      semanticType: "aws-security",
      name: "Secrets Manager",
      awsService: "secrets-manager",
      parentId: "vpc-producao",
      tier: "compute",
    },
    {
      id: "cloudwatch-monitor",
      semanticType: "aws-management",
      name: "CloudWatch Monitoramento",
      awsService: "cloudwatch",
      parentId: "vpc-producao",
      tier: "compute",
    },
    {
      id: "aplicacao-externa",
      semanticType: "external-system",
      name: "Aplicação Externa",
      parentId: null,
      tier: "external",
    },
    {
      id: "usuario",
      semanticType: "person",
      name: "Usuário",
      parentId: null,
      tier: "external",
    },
  ],
  edges: [
    {
      id: "usuario-to-route53",
      sourceId: "usuario",
      targetId: "route-53",
      label: "acessa domínio",
    },
    {
      id: "route53-to-cloudfront",
      sourceId: "route-53",
      targetId: "cloudfront-cdn",
      label: "resolve para CDN",
    },
    {
      id: "cloudfront-to-alb1",
      sourceId: "cloudfront-cdn",
      targetId: "alb-1",
      label: "HTTP/HTTPS",
    },
    {
      id: "cloudfront-to-alb2",
      sourceId: "cloudfront-cdn",
      targetId: "alb-2",
      label: "HTTP/HTTPS",
    },
    {
      id: "alb1-to-fargate1",
      sourceId: "alb-1",
      targetId: "fargate-service-1",
      label: "balanceia requisições",
    },
    {
      id: "alb2-to-fargate2",
      sourceId: "alb-2",
      targetId: "fargate-service-2",
      label: "balanceia requisições",
    },
    {
      id: "alb1-to-lambda1",
      sourceId: "alb-1",
      targetId: "lambda-func-app",
      label: "invoca função",
    },
    {
      id: "alb2-to-lambda2",
      sourceId: "alb-2",
      targetId: "lambda-func-app2",
      label: "invoca função",
    },
    {
      id: "fargate1-to-rds",
      sourceId: "fargate-service-1",
      targetId: "rds-multi-az",
      label: "leitura/escrita",
    },
    {
      id: "fargate2-to-rds",
      sourceId: "fargate-service-2",
      targetId: "rds-multi-az",
      label: "leitura/escrita",
    },
    {
      id: "lambda1-to-rds",
      sourceId: "lambda-func-app",
      targetId: "rds-multi-az",
      label: "consulta",
    },
    {
      id: "lambda2-to-rds",
      sourceId: "lambda-func-app2",
      targetId: "rds-multi-az",
      label: "consulta",
    },
    {
      id: "fargate1-to-s3app",
      sourceId: "fargate-service-1",
      targetId: "s3-bucket-app",
      label: "salva arquivos",
    },
    {
      id: "fargate2-to-s3app",
      sourceId: "fargate-service-2",
      targetId: "s3-bucket-app",
      label: "lê arquivos",
    },
    {
      id: "lambda1-to-s3static",
      sourceId: "lambda-func-app",
      targetId: "s3-bucket-static",
      label: "upload de assets",
    },
    {
      id: "cloudfront-to-s3static",
      sourceId: "cloudfront-cdn",
      targetId: "s3-bucket-static",
      label: "cache de conteúdo",
    },
    {
      id: "fargate1-to-sqs-entrada",
      sourceId: "fargate-service-1",
      targetId: "sqs-fila-entrada",
      label: "envia mensagens",
    },
    {
      id: "fargate2-to-sqs-processo",
      sourceId: "fargate-service-2",
      targetId: "sqs-fila-processo",
      label: "publica eventos",
    },
    {
      id: "lambda-bg-to-sqs-processo",
      sourceId: "lambda-func-bg",
      targetId: "sqs-fila-processo",
      label: "consome mensagens",
    },
    {
      id: "fargate1-to-sns1",
      sourceId: "fargate-service-1",
      targetId: "sns-topico-app",
      label: "notificações",
    },
    {
      id: "fargate2-to-sns2",
      sourceId: "fargate-service-2",
      targetId: "sns-topico-eventos",
      label: "dispara eventos",
    },
    {
      id: "lambda1-to-secrets",
      sourceId: "lambda-func-app",
      targetId: "secrets-manager",
      label: "busca segredos",
    },
    {
      id: "lambda2-to-secrets",
      sourceId: "lambda-func-app2",
      targetId: "secrets-manager",
      label: "busca segredos",
    },
    {
      id: "fargate1-to-secrets",
      sourceId: "fargate-service-1",
      targetId: "secrets-manager",
      label: "usa secrets",
    },
    {
      id: "fargate2-to-secrets",
      sourceId: "fargate-service-2",
      targetId: "secrets-manager",
      label: "usa secrets",
    },
    {
      id: "fargate1-to-cloudwatch",
      sourceId: "fargate-service-1",
      targetId: "cloudwatch-monitor",
      label: "logs/metricas",
    },
    {
      id: "fargate2-to-cloudwatch",
      sourceId: "fargate-service-2",
      targetId: "cloudwatch-monitor",
      label: "logs/metricas",
    },
    {
      id: "lambda-bg-to-cloudwatch",
      sourceId: "lambda-func-bg",
      targetId: "cloudwatch-monitor",
      label: "envia logs",
    },
    {
      id: "lambda1-to-sns1",
      sourceId: "lambda-func-app",
      targetId: "sns-topico-app",
      label: "publica tópicos",
    },
    {
      id: "lambda2-to-sqs-entrada",
      sourceId: "lambda-func-app2",
      targetId: "sqs-fila-entrada",
      label: "envia jobs",
    },
    {
      id: "fargate1-to-nat1",
      sourceId: "fargate-service-1",
      targetId: "nat-1",
      label: "acesso internet",
    },
    {
      id: "fargate2-to-nat2",
      sourceId: "fargate-service-2",
      targetId: "nat-2",
      label: "acesso internet",
    },
    {
      id: "albs-to-s3-logs",
      sourceId: "alb-1",
      targetId: "s3-bucket-logs",
      label: "logs do ALB",
    },
    {
      id: "albs2-to-s3-logs",
      sourceId: "alb-2",
      targetId: "s3-bucket-logs",
      label: "logs do ALB",
    },
    {
      id: "cloudfront-to-s3-logs",
      sourceId: "cloudfront-cdn",
      targetId: "s3-bucket-logs",
      label: "logs de acesso",
    },
    {
      id: "sns1-to-app-ext",
      sourceId: "sns-topico-app",
      targetId: "aplicacao-externa",
      label: "entrega notificações",
    },
    {
      id: "sns2-to-app-ext",
      sourceId: "sns-topico-eventos",
      targetId: "aplicacao-externa",
      label: "publica eventos",
    },
  ],
};
