import type { DiagramIR } from "@/features/llm/ir/ir.types";

/**
 * Case B (AWS deployment, ~40 nodes), run 2.
 *
 * Captured verbatim from a real model response on 2026-08-27 and frozen here.
 * Not authored, not repaired, not tidied: what the model wrote is what runs.
 * Provenance and the run's measurements are in
 * `docs/fatia1-transporte/B-run2.ir.json` and `B-run2.measure.json`.
 */
export const bRun2: DiagramIR = {
  type: "aws-deployment",
  nodes: [
    {
      id: "webapp-vpc",
      semanticType: "aws-vpc",
      name: "VPC Produção",
      awsService: "vpc",
      parentId: null,
      isBoundary: true,
      tier: "edge",
    },
    {
      id: "az1",
      semanticType: "aws-az",
      name: "us-east-1a",
      parentId: "webapp-vpc",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "az2",
      semanticType: "aws-az",
      name: "us-east-1b",
      parentId: "webapp-vpc",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "public-subnet-1",
      semanticType: "aws-public-subnet",
      name: "Sub-rede pública 1",
      awsService: "public-subnet",
      parentId: "az1",
      isBoundary: true,
      tier: "edge",
    },
    {
      id: "public-subnet-2",
      semanticType: "aws-public-subnet",
      name: "Sub-rede pública 2",
      awsService: "public-subnet",
      parentId: "az2",
      isBoundary: true,
      tier: "edge",
    },
    {
      id: "private-subnet-1",
      semanticType: "aws-private-subnet",
      name: "Sub-rede privada 1",
      awsService: "private-subnet",
      parentId: "az1",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "private-subnet-2",
      semanticType: "aws-private-subnet",
      name: "Sub-rede privada 2",
      awsService: "private-subnet",
      parentId: "az2",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "natgw-1",
      semanticType: "aws-networking",
      name: "NAT Gateway 1",
      awsService: "vpc",
      parentId: "public-subnet-1",
      tier: "edge",
    },
    {
      id: "natgw-2",
      semanticType: "aws-networking",
      name: "NAT Gateway 2",
      awsService: "vpc",
      parentId: "public-subnet-2",
      tier: "edge",
    },
    {
      id: "alb",
      semanticType: "aws-networking",
      name: "Application Load Balancer",
      awsService: "elb",
      parentId: "public-subnet-1",
      tier: "edge",
    },
    {
      id: "alb-2",
      semanticType: "aws-networking",
      name: "Application Load Balancer AZ2",
      awsService: "elb",
      parentId: "public-subnet-2",
      tier: "edge",
    },
    {
      id: "ecs-fargate-1",
      semanticType: "aws-compute",
      name: "Serviço ECS Fargate 1",
      awsService: "fargate",
      parentId: "private-subnet-1",
      tier: "compute",
    },
    {
      id: "ecs-fargate-2",
      semanticType: "aws-compute",
      name: "Serviço ECS Fargate 2",
      awsService: "fargate",
      parentId: "private-subnet-2",
      tier: "compute",
    },
    {
      id: "lambda-1",
      semanticType: "aws-compute",
      name: "Função Lambda 1",
      awsService: "lambda",
      parentId: "private-subnet-1",
      tier: "compute",
    },
    {
      id: "lambda-2",
      semanticType: "aws-compute",
      name: "Função Lambda 2",
      awsService: "lambda",
      parentId: "private-subnet-2",
      tier: "compute",
    },
    {
      id: "rds-primary",
      semanticType: "aws-database",
      name: "RDS PostgreSQL Primário",
      awsService: "rds",
      parentId: "private-subnet-1",
      tier: "data",
    },
    {
      id: "rds-secondary",
      semanticType: "aws-database",
      name: "RDS PostgreSQL Réplica",
      awsService: "rds",
      parentId: "private-subnet-2",
      tier: "data",
    },
    {
      id: "s3-assets",
      semanticType: "aws-storage",
      name: "S3 - Assets Estáticos",
      awsService: "s3",
      parentId: "webapp-vpc",
      tier: "data",
    },
    {
      id: "s3-backups",
      semanticType: "aws-storage",
      name: "S3 - Backups",
      awsService: "s3",
      parentId: "webapp-vpc",
      tier: "data",
    },
    {
      id: "s3-logs",
      semanticType: "aws-storage",
      name: "S3 - Logs",
      awsService: "s3",
      parentId: "webapp-vpc",
      tier: "data",
    },
    {
      id: "sqs-queue-1",
      semanticType: "aws-integration",
      name: "Fila SQS 1",
      awsService: "sqs",
      parentId: "webapp-vpc",
      tier: "integration",
    },
    {
      id: "sqs-queue-2",
      semanticType: "aws-integration",
      name: "Fila SQS 2",
      awsService: "sqs",
      parentId: "webapp-vpc",
      tier: "integration",
    },
    {
      id: "sns-topic-1",
      semanticType: "aws-integration",
      name: "Tópico SNS Notificações",
      awsService: "sns",
      parentId: "webapp-vpc",
      tier: "integration",
    },
    {
      id: "sns-topic-2",
      semanticType: "aws-integration",
      name: "Tópico SNS Alarmes",
      awsService: "sns",
      parentId: "webapp-vpc",
      tier: "integration",
    },
    {
      id: "cloudfront",
      semanticType: "aws-networking",
      name: "CloudFront CDN",
      awsService: "cloudfront",
      parentId: null,
      tier: "edge",
    },
    {
      id: "route53",
      semanticType: "aws-networking",
      name: "Route 53",
      awsService: "route53",
      parentId: null,
      tier: "edge",
    },
    {
      id: "secretsmgr",
      semanticType: "aws-security",
      name: "Secrets Manager",
      awsService: "secrets-manager",
      parentId: "webapp-vpc",
      tier: "compute",
    },
    {
      id: "cloudwatch",
      semanticType: "aws-management",
      name: "CloudWatch",
      awsService: "cloudwatch",
      parentId: "webapp-vpc",
      tier: "compute",
    },
    {
      id: "ecs-taskdef-1",
      semanticType: "aws-containers",
      name: "Task Definition 1",
      awsService: "ecs-2",
      parentId: "webapp-vpc",
      tier: "compute",
    },
    {
      id: "ecs-taskdef-2",
      semanticType: "aws-containers",
      name: "Task Definition 2",
      awsService: "ecs-2",
      parentId: "webapp-vpc",
      tier: "compute",
    },
    {
      id: "ecr-registry",
      semanticType: "aws-containers",
      name: "ECR Registry",
      awsService: "ecr",
      parentId: "webapp-vpc",
      tier: "compute",
    },
    {
      id: "ecs-cluster",
      semanticType: "aws-containers",
      name: "ECS Cluster",
      awsService: "ecs-2",
      parentId: "webapp-vpc",
      tier: "compute",
    },
    {
      id: "application-logs",
      semanticType: "aws-storage",
      name: "S3 - Application Logs",
      awsService: "s3",
      parentId: "webapp-vpc",
      tier: "data",
    },
    {
      id: "static-website",
      semanticType: "aws-storage",
      name: "S3 - Site Estático",
      awsService: "s3",
      parentId: "webapp-vpc",
      tier: "data",
    },
    {
      id: "eventbridge-bus",
      semanticType: "aws-integration",
      name: "EventBridge",
      awsService: "eventbridge",
      parentId: "webapp-vpc",
      tier: "integration",
    },
    {
      id: "stepfunctions",
      semanticType: "aws-integration",
      name: "Step Functions",
      awsService: "step-functions",
      parentId: "webapp-vpc",
      tier: "integration",
    },
    {
      id: "cloudtrail",
      semanticType: "aws-management",
      name: "CloudTrail",
      awsService: "cloudtrail",
      parentId: "webapp-vpc",
      tier: "compute",
    },
    {
      id: "iam-roles",
      semanticType: "aws-security",
      name: "IAM Roles",
      awsService: "iam",
      parentId: "webapp-vpc",
      tier: "compute",
    },
    {
      id: "kms",
      semanticType: "aws-security",
      name: "KMS",
      awsService: "kms",
      parentId: "webapp-vpc",
      tier: "compute",
    },
    {
      id: "cw-alarms",
      semanticType: "aws-management",
      name: "CloudWatch Alarms",
      awsService: "cloudwatch",
      parentId: "webapp-vpc",
      tier: "compute",
    },
    {
      id: "paramstore",
      semanticType: "aws-management",
      name: "Parameter Store",
      awsService: "systems-manager",
      parentId: "webapp-vpc",
      tier: "compute",
    },
    {
      id: "backup-vault",
      semanticType: "aws-storage",
      name: "Backup Vault",
      awsService: "backup",
      parentId: "webapp-vpc",
      tier: "data",
    },
  ],
  edges: [
    {
      id: "route53-to-cf",
      sourceId: "route53",
      targetId: "cloudfront",
      label: "Direciona tráfego",
    },
    {
      id: "cloudfront-to-alb",
      sourceId: "cloudfront",
      targetId: "alb",
      label: "Redireciona requisições",
    },
    {
      id: "cloudfront-to-static-website",
      sourceId: "cloudfront",
      targetId: "static-website",
      label: "Distribui site estático",
    },
    {
      id: "alb-to-ecs",
      sourceId: "alb",
      targetId: "ecs-fargate-1",
      label: "Encaminha tráfego",
    },
    {
      id: "alb2-to-ecs2",
      sourceId: "alb-2",
      targetId: "ecs-fargate-2",
      label: "Encaminha tráfego",
    },
    {
      id: "ecs-1-to-rds-primary",
      sourceId: "ecs-fargate-1",
      targetId: "rds-primary",
      label: "Leitura/Gravação",
    },
    {
      id: "ecs-2-to-rds-replica",
      sourceId: "ecs-fargate-2",
      targetId: "rds-secondary",
      label: "Leitura",
    },
    {
      id: "ecs-1-to-s3-assets",
      sourceId: "ecs-fargate-1",
      targetId: "s3-assets",
      label: "Upload/Download",
    },
    {
      id: "ecs-2-to-s3-assets",
      sourceId: "ecs-fargate-2",
      targetId: "s3-assets",
      label: "Upload/Download",
    },
    {
      id: "ecs-1-to-sqs",
      sourceId: "ecs-fargate-1",
      targetId: "sqs-queue-1",
      label: "Envia mensagens",
    },
    {
      id: "ecs-2-to-sqs",
      sourceId: "ecs-fargate-2",
      targetId: "sqs-queue-2",
      label: "Envia mensagens",
    },
    {
      id: "ecs-1-to-sns",
      sourceId: "ecs-fargate-1",
      targetId: "sns-topic-1",
      label: "Publica eventos",
    },
    {
      id: "ecs-2-to-sns",
      sourceId: "ecs-fargate-2",
      targetId: "sns-topic-2",
      label: "Publica alarmes",
    },
    {
      id: "ecs-1-to-lambda-1",
      sourceId: "ecs-fargate-1",
      targetId: "lambda-1",
      label: "Invoca função",
    },
    {
      id: "ecs-2-to-lambda-2",
      sourceId: "ecs-fargate-2",
      targetId: "lambda-2",
      label: "Invoca função",
    },
    {
      id: "lambda-1-to-sqs",
      sourceId: "lambda-1",
      targetId: "sqs-queue-1",
      label: "Envia mensagens",
    },
    {
      id: "lambda-2-to-sns",
      sourceId: "lambda-2",
      targetId: "sns-topic-1",
      label: "Publica eventos",
    },
    {
      id: "ecs-1-to-secrets",
      sourceId: "ecs-fargate-1",
      targetId: "secretsmgr",
      label: "Consulta segredos",
    },
    {
      id: "ecs-2-to-secrets",
      sourceId: "ecs-fargate-2",
      targetId: "secretsmgr",
      label: "Consulta segredos",
    },
    {
      id: "ecs-1-to-cw",
      sourceId: "ecs-fargate-1",
      targetId: "cloudwatch",
      label: "Logs/Métricas",
    },
    {
      id: "ecs-2-to-cw",
      sourceId: "ecs-fargate-2",
      targetId: "cloudwatch",
      label: "Logs/Métricas",
    },
    {
      id: "lambda-1-to-cw",
      sourceId: "lambda-1",
      targetId: "cloudwatch",
      label: "Logs",
    },
    {
      id: "lambda-2-to-cw",
      sourceId: "lambda-2",
      targetId: "cloudwatch",
      label: "Logs",
    },
    {
      id: "sqs-to-lambda-1",
      sourceId: "sqs-queue-1",
      targetId: "lambda-1",
      label: "Desencadeia processamento",
    },
    {
      id: "sns-to-lambda-2",
      sourceId: "sns-topic-1",
      targetId: "lambda-2",
      label: "Desencadeia função",
    },
    {
      id: "rds-to-backup-s3",
      sourceId: "rds-primary",
      targetId: "s3-backups",
      label: "Backup automatizado",
    },
    {
      id: "application-logs-to-cw",
      sourceId: "application-logs",
      targetId: "cloudwatch",
      label: "Monitoramento",
    },
    {
      id: "ecs-fargate-1-to-taskdef",
      sourceId: "ecs-fargate-1",
      targetId: "ecs-taskdef-1",
      label: "Executa tarefa",
    },
    {
      id: "ecs-fargate-2-to-taskdef",
      sourceId: "ecs-fargate-2",
      targetId: "ecs-taskdef-2",
      label: "Executa tarefa",
    },
    {
      id: "ecr-to-taskdef-1",
      sourceId: "ecr-registry",
      targetId: "ecs-taskdef-1",
      label: "Fornece imagem",
    },
    {
      id: "ecr-to-taskdef-2",
      sourceId: "ecr-registry",
      targetId: "ecs-taskdef-2",
      label: "Fornece imagem",
    },
    {
      id: "ecs-cluster-to-ecs-fargate-1",
      sourceId: "ecs-cluster",
      targetId: "ecs-fargate-1",
      label: "Escalabilidade",
    },
    {
      id: "ecs-cluster-to-ecs-fargate-2",
      sourceId: "ecs-cluster",
      targetId: "ecs-fargate-2",
      label: "Escalabilidade",
    },
  ],
};
