import type { DiagramIR } from "@/features/llm/ir/ir.types";

/**
 * Case B (AWS deployment, ~40 nodes), run 1.
 *
 * Captured verbatim from a real model response on 2026-08-27 and frozen here.
 * Not authored, not repaired, not tidied: what the model wrote is what runs.
 * Provenance and the run's measurements are in
 * `docs/fatia1-transporte/B-run1.ir.json` and `B-run1.measure.json`.
 */
export const bRun1: DiagramIR = {
  type: "aws-deployment",
  nodes: [
    {
      id: "webapp-vpc",
      semanticType: "aws-vpc",
      name: "VPC da Aplicação Web",
      awsService: "vpc",
      parentId: null,
      isBoundary: true,
      tier: "edge",
    },
    {
      id: "az-a",
      semanticType: "aws-az",
      name: "us-east-1a",
      parentId: "webapp-vpc",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "az-b",
      semanticType: "aws-az",
      name: "us-east-1b",
      parentId: "webapp-vpc",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "public-a",
      semanticType: "aws-public-subnet",
      name: "Subnet Pública A",
      awsService: "public-subnet",
      parentId: "az-a",
      isBoundary: true,
      tier: "edge",
    },
    {
      id: "private-a",
      semanticType: "aws-private-subnet",
      name: "Subnet Privada A",
      awsService: "private-subnet",
      parentId: "az-a",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "public-b",
      semanticType: "aws-public-subnet",
      name: "Subnet Pública B",
      awsService: "public-subnet",
      parentId: "az-b",
      isBoundary: true,
      tier: "edge",
    },
    {
      id: "private-b",
      semanticType: "aws-private-subnet",
      name: "Subnet Privada B",
      awsService: "private-subnet",
      parentId: "az-b",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "cloudfront",
      semanticType: "aws-networking",
      name: "CloudFront CDN",
      awsService: "cloudfront",
      parentId: "webapp-vpc",
      tier: "edge",
    },
    {
      id: "route53",
      semanticType: "aws-networking",
      name: "Route 53",
      awsService: "route53",
      parentId: "webapp-vpc",
      tier: "edge",
    },
    {
      id: "alb-a",
      semanticType: "aws-networking",
      name: "ALB Zona A",
      awsService: "elb",
      parentId: "public-a",
      tier: "edge",
    },
    {
      id: "natgw-a",
      semanticType: "aws-networking",
      name: "NAT Gateway A",
      awsService: "nat-gateway",
      parentId: "public-a",
      tier: "ingress",
    },
    {
      id: "alb-b",
      semanticType: "aws-networking",
      name: "ALB Zona B",
      awsService: "elb",
      parentId: "public-b",
      tier: "edge",
    },
    {
      id: "natgw-b",
      semanticType: "aws-networking",
      name: "NAT Gateway B",
      awsService: "nat-gateway",
      parentId: "public-b",
      tier: "ingress",
    },
    {
      id: "ecs-fargate-a",
      semanticType: "aws-compute",
      name: "ECS Fargate A",
      awsService: "fargate",
      parentId: "private-a",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "lambda-a-1",
      semanticType: "aws-compute",
      name: "Lambda A 1",
      awsService: "lambda",
      parentId: "private-a",
      tier: "compute",
    },
    {
      id: "lambda-a-2",
      semanticType: "aws-compute",
      name: "Lambda A 2",
      awsService: "lambda",
      parentId: "private-a",
      tier: "compute",
    },
    {
      id: "ecs-fargate-b",
      semanticType: "aws-compute",
      name: "ECS Fargate B",
      awsService: "fargate",
      parentId: "private-b",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "lambda-b-1",
      semanticType: "aws-compute",
      name: "Lambda B 1",
      awsService: "lambda",
      parentId: "private-b",
      tier: "compute",
    },
    {
      id: "lambda-b-2",
      semanticType: "aws-compute",
      name: "Lambda B 2",
      awsService: "lambda",
      parentId: "private-b",
      tier: "compute",
    },
    {
      id: "rds-db-a",
      semanticType: "aws-database",
      name: "RDS (Primário)",
      awsService: "rds",
      parentId: "private-a",
      tier: "data",
    },
    {
      id: "rds-db-b",
      semanticType: "aws-database",
      name: "RDS (Rélica)",
      awsService: "rds",
      parentId: "private-b",
      tier: "data",
    },
    {
      id: "s3-site",
      semanticType: "aws-storage",
      name: "S3 Site Estático",
      awsService: "s3",
      parentId: "webapp-vpc",
      tier: "data",
    },
    {
      id: "s3-upload",
      semanticType: "aws-storage",
      name: "S3 Uploads",
      awsService: "s3",
      parentId: "webapp-vpc",
      tier: "data",
    },
    {
      id: "s3-backup",
      semanticType: "aws-storage",
      name: "S3 Backup",
      awsService: "s3",
      parentId: "webapp-vpc",
      tier: "data",
    },
    {
      id: "sqs-a",
      semanticType: "aws-integration",
      name: "Fila SQS A",
      awsService: "sqs",
      parentId: "private-a",
      tier: "integration",
    },
    {
      id: "sqs-b",
      semanticType: "aws-integration",
      name: "Fila SQS B",
      awsService: "sqs",
      parentId: "private-b",
      tier: "integration",
    },
    {
      id: "sns-a",
      semanticType: "aws-integration",
      name: "Tópico SNS A",
      awsService: "sns",
      parentId: "private-a",
      tier: "integration",
    },
    {
      id: "sns-b",
      semanticType: "aws-integration",
      name: "Tópico SNS B",
      awsService: "sns",
      parentId: "private-b",
      tier: "integration",
    },
    {
      id: "cloudwatch",
      semanticType: "aws-management",
      name: "CloudWatch",
      awsService: "cloudwatch",
      parentId: "webapp-vpc",
      tier: "compute",
    },
    {
      id: "secrets-manager",
      semanticType: "aws-security",
      name: "Secrets Manager",
      awsService: "secrets-manager",
      parentId: "webapp-vpc",
      tier: "compute",
    },
    {
      id: "ecs-task-a-1",
      semanticType: "aws-compute",
      name: "ECS Task A1",
      awsService: "fargate",
      parentId: "ecs-fargate-a",
      tier: "compute",
    },
    {
      id: "ecs-task-a-2",
      semanticType: "aws-compute",
      name: "ECS Task A2",
      awsService: "fargate",
      parentId: "ecs-fargate-a",
      tier: "compute",
    },
    {
      id: "ecs-task-b-1",
      semanticType: "aws-compute",
      name: "ECS Task B1",
      awsService: "fargate",
      parentId: "ecs-fargate-b",
      tier: "compute",
    },
    {
      id: "ecs-task-b-2",
      semanticType: "aws-compute",
      name: "ECS Task B2",
      awsService: "fargate",
      parentId: "ecs-fargate-b",
      tier: "compute",
    },
    {
      id: "internal-alb",
      semanticType: "aws-networking",
      name: "ALB Interno",
      awsService: "elb",
      parentId: "webapp-vpc",
      tier: "ingress",
    },
    {
      id: "cloudwatch-log-a",
      semanticType: "aws-management",
      name: "Logs CloudWatch A",
      awsService: "cloudwatch",
      parentId: "private-a",
      tier: "compute",
    },
    {
      id: "cloudwatch-log-b",
      semanticType: "aws-management",
      name: "Logs CloudWatch B",
      awsService: "cloudwatch",
      parentId: "private-b",
      tier: "compute",
    },
    {
      id: "secrets-a",
      semanticType: "aws-security",
      name: "Secrets A",
      awsService: "secrets-manager",
      parentId: "private-a",
      tier: "compute",
    },
    {
      id: "secrets-b",
      semanticType: "aws-security",
      name: "Secrets B",
      awsService: "secrets-manager",
      parentId: "private-b",
      tier: "compute",
    },
  ],
  edges: [
    {
      id: "route53-to-cloudfront",
      sourceId: "route53",
      targetId: "cloudfront",
      label: "resolve domínio",
    },
    {
      id: "cloudfront-to-alb-a",
      sourceId: "cloudfront",
      targetId: "alb-a",
      label: "repassa HTTP/HTTPS",
    },
    {
      id: "cloudfront-to-alb-b",
      sourceId: "cloudfront",
      targetId: "alb-b",
      label: "repassa HTTP/HTTPS",
    },
    {
      id: "alb-a-to-ecs-fargate-a",
      sourceId: "alb-a",
      targetId: "ecs-fargate-a",
      label: "distribui tráfego",
    },
    {
      id: "alb-b-to-ecs-fargate-b",
      sourceId: "alb-b",
      targetId: "ecs-fargate-b",
      label: "distribui tráfego",
    },
    {
      id: "alb-a-to-lambda-a1",
      sourceId: "alb-a",
      targetId: "lambda-a-1",
      label: "invoca Lambda",
    },
    {
      id: "alb-b-to-lambda-b1",
      sourceId: "alb-b",
      targetId: "lambda-b-1",
      label: "invoca Lambda",
    },
    {
      id: "ecs-fargate-a-to-rds",
      sourceId: "ecs-fargate-a",
      targetId: "rds-db-a",
      label: "consulta banco",
    },
    {
      id: "ecs-fargate-b-to-rds",
      sourceId: "ecs-fargate-b",
      targetId: "rds-db-b",
      label: "consulta banco",
    },
    {
      id: "lambda-a-1-to-sqs-a",
      sourceId: "lambda-a-1",
      targetId: "sqs-a",
      label: "envia mensagens",
    },
    {
      id: "lambda-b-1-to-sqs-b",
      sourceId: "lambda-b-1",
      targetId: "sqs-b",
      label: "envia mensagens",
    },
    {
      id: "ecs-task-a-1-to-sqs-a",
      sourceId: "ecs-task-a-1",
      targetId: "sqs-a",
      label: "produz mensagem",
    },
    {
      id: "ecs-task-b-1-to-sqs-b",
      sourceId: "ecs-task-b-1",
      targetId: "sqs-b",
      label: "produz mensagem",
    },
    {
      id: "ecs-fargate-a-to-sns-a",
      sourceId: "ecs-fargate-a",
      targetId: "sns-a",
      label: "publica tópicos",
    },
    {
      id: "ecs-fargate-b-to-sns-b",
      sourceId: "ecs-fargate-b",
      targetId: "sns-b",
      label: "publica tópicos",
    },
    {
      id: "ecs-fargate-a-to-s3-upload",
      sourceId: "ecs-fargate-a",
      targetId: "s3-upload",
      label: "faz upload",
    },
    {
      id: "ecs-fargate-b-to-s3-upload",
      sourceId: "ecs-fargate-b",
      targetId: "s3-upload",
      label: "faz upload",
    },
    {
      id: "lambda-a-2-to-s3-backup",
      sourceId: "lambda-a-2",
      targetId: "s3-backup",
      label: "salva dados",
    },
    {
      id: "lambda-b-2-to-s3-backup",
      sourceId: "lambda-b-2",
      targetId: "s3-backup",
      label: "salva dados",
    },
    {
      id: "ecs-fargate-a-to-secrets",
      sourceId: "ecs-fargate-a",
      targetId: "secrets-manager",
      label: "busca segredo",
    },
    {
      id: "ecs-fargate-b-to-secrets",
      sourceId: "ecs-fargate-b",
      targetId: "secrets-manager",
      label: "busca segredo",
    },
    {
      id: "ecs-fargate-a-to-cloudwatch",
      sourceId: "ecs-fargate-a",
      targetId: "cloudwatch",
      label: "envia logs",
    },
    {
      id: "ecs-fargate-b-to-cloudwatch",
      sourceId: "ecs-fargate-b",
      targetId: "cloudwatch",
      label: "envia logs",
    },
    {
      id: "internal-alb-to-ecs-fargate-a",
      sourceId: "internal-alb",
      targetId: "ecs-fargate-a",
      label: "balança internamente",
    },
    {
      id: "internal-alb-to-ecs-fargate-b",
      sourceId: "internal-alb",
      targetId: "ecs-fargate-b",
      label: "balança internamente",
    },
    {
      id: "natgw-a-to-private-a",
      sourceId: "natgw-a",
      targetId: "private-a",
      label: "acesso internet",
    },
    {
      id: "natgw-b-to-private-b",
      sourceId: "natgw-b",
      targetId: "private-b",
      label: "acesso internet",
    },
  ],
};
