openapi: 3.1.0
info:
  title: BusinessService
  version: v1
  description: "Serviço de negócio"

components:
  schemas:
    BusinessServiceSpec:
      type: object
      required:
        - description
      properties:
        description:
          type: string
        displayName:
          type: string
          description: Friendly display name for the business service
