export { CollabProvider, useCollab } from "./components/CollabProvider";
export { CollabEditingWarning } from "./components/CollabEditingWarning";
export { CollabCursors } from "./components/CollabCursors";
export { CollabToolbar } from "./components/CollabToolbar";
export { CollabStartModal } from "./components/CollabStartModal";
export { CollabJoinModal } from "./components/CollabJoinModal";
export { CollabSessionClosedModal } from "./components/CollabSessionClosedModal";
export { CollabStatusIndicator } from "./components/CollabStatusIndicator";
export { CollabRoom } from "./components/CollabRoom";
export { remoteLayoutUpdates } from "./hooks/useCollabStoreSync";
export { useCollabHighlight } from "./hooks/useCollabHighlight";
export type { CollabElementHighlight } from "./hooks/useCollabHighlight";
export { useCollabStore } from "./store/collab.store";
export type * from "./types";
