import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import type { Component, Diagram, NodeLayout } from "@/features/diagram";
import { applySeedAutoLayout } from "./applySeedAutoLayout";
import { buildCatalogDiagram } from "./catalog";
import { buildContextDiagram } from "./context";
import { buildHubContainerDiagram } from "./container-hub";
import { buildLedgerContainerDiagram } from "./container-ledger";
import { buildMerchantContainerDiagram } from "./container-merchant";
import { buildRiskContainerDiagram } from "./container-risk";
import { buildHubDeploymentDiagram } from "./deployment-hub";
import { buildLedgerDeploymentDiagram } from "./deployment-ledger";
import { buildMerchantDeploymentDiagram } from "./deployment-merchant";
import { buildRiskDeploymentDiagram } from "./deployment-risk";
import { D_DP_HUB } from "./ids";

/**
 * Regenerates `layouts.generated.ts` with the same ELK pipeline as the canvas
 * auto-layout button (`fromDiagram` → `layout` → `toAppliedLayouts`).
 *
 * `d-pl-dp-hub` is pinned from a hand-tuned export (api-group outside the VPC)
 * — ELK is skipped for that id so regen does not undo the placement.
 *
 * Run:
 *   npx vitest run src/fixtures/seeds/pixledger/generate-layouts.test.ts
 */

/** Diagrams whose builder `nodeLayouts` are the source of truth (no ELK). */
const PINNED_LAYOUT_IDS = new Set<string>([D_DP_HUB]);

interface LaidOutSlice {
  nodeLayouts: Record<string, NodeLayout>;
  viewport: Diagram["viewport"];
  handleOrder: Record<string, { outgoing: string[]; incoming: string[] }>;
}

function extractHandleOrder(components: Record<string, Component>): LaidOutSlice["handleOrder"] {
  const order: LaidOutSlice["handleOrder"] = {};
  for (const [id, component] of Object.entries(components)) {
    if (!component.handleOrder) continue;
    order[id] = {
      outgoing: [...(component.handleOrder.outgoing ?? [])],
      incoming: [...(component.handleOrder.incoming ?? [])],
    };
  }
  return order;
}

function childrenInsideParents(diagram: Diagram): string[] {
  const violations: string[] = [];
  const { components } = diagram.snapshot;
  const { nodeLayouts } = diagram;

  for (const component of Object.values(components)) {
    if (!component.parentId) continue;
    const parent = components[component.parentId];
    if (!parent || parent.type !== "panel") continue;

    const childLayout = nodeLayouts[component.id];
    const parentLayout = nodeLayouts[component.parentId];
    if (!childLayout || !parentLayout) continue;

    const parentW = parentLayout.width ?? 0;
    const parentH = parentLayout.height ?? 0;
    const childW = childLayout.width ?? 180;
    const childH = childLayout.height ?? 80;
    const pad = 8; // ELK compound boxes can sit a few px past the fitted panel edge

    if (childLayout.x < -pad) {
      violations.push(`${component.id} overflows left of ${parent.id}`);
    }
    if (childLayout.y < -pad) {
      violations.push(`${component.id} overflows top of ${parent.id}`);
    }
    if (childLayout.x + childW > parentW + pad) {
      violations.push(`${component.id} overflows right of ${parent.id}`);
    }
    if (childLayout.y + childH > parentH + pad) {
      violations.push(`${component.id} overflows bottom of ${parent.id}`);
    }
  }
  return violations;
}

function serializeLayouts(slices: Record<string, LaidOutSlice>): string {
  const body = JSON.stringify(slices, null, 2);
  return `/**
 * AUTO-GENERATED by generate-layouts.test.ts — do not edit by hand.
 * Regenerate: npx vitest run src/fixtures/seeds/pixledger/generate-layouts.test.ts
 */
import type { NodeLayout } from "@/features/diagram";

export interface SeedLaidOutSlice {
  nodeLayouts: Record<string, NodeLayout>;
  viewport: { x: number; y: number; zoom: number };
  handleOrder: Record<string, { outgoing: string[]; incoming: string[] }>;
}

export const SEED_PL_LAID_OUT: Record<string, SeedLaidOutSlice> = ${body};
`;
}

describe("PixLedger seed auto-layout generation", () => {
  it("lays out every diagram, keeps children indented in panels, and writes layouts.generated.ts", async () => {
    const builders = [
      buildContextDiagram,
      buildHubContainerDiagram,
      buildLedgerContainerDiagram,
      buildRiskContainerDiagram,
      buildMerchantContainerDiagram,
      buildHubDeploymentDiagram,
      buildLedgerDeploymentDiagram,
      buildRiskDeploymentDiagram,
      buildMerchantDeploymentDiagram,
      buildCatalogDiagram,
    ];

    const slices: Record<string, LaidOutSlice> = {};
    for (const build of builders) {
      const raw = build();
      const laidOut = PINNED_LAYOUT_IDS.has(raw.id) ? raw : await applySeedAutoLayout(raw);
      expect(childrenInsideParents(laidOut), laidOut.id).toEqual([]);

      // Every non-endpoint component must receive an ELK box. Endpoints live
      // under api-groups and are excluded from the layout graph — they keep the
      // builder's relative coords so the seed never boots with missing boxes.
      const missing = Object.keys(raw.snapshot.components).filter((id) => {
        if (laidOut.nodeLayouts[id]) return false;
        return true;
      });
      expect({ diagram: laidOut.id, missing }, laidOut.id).toEqual({
        diagram: laidOut.id,
        missing: [],
      });

      // Generated file must not keep coords for deleted components.
      const liveIds = new Set(Object.keys(raw.snapshot.components));
      const stale = Object.keys(laidOut.nodeLayouts).filter((id) => !liveIds.has(id));
      expect({ diagram: laidOut.id, stale }, laidOut.id).toEqual({
        diagram: laidOut.id,
        stale: [],
      });

      // Strip stale before write (defensive — merge should already be clean).
      const nodeLayouts: Record<string, NodeLayout> = {};
      for (const id of liveIds) {
        const box = laidOut.nodeLayouts[id];
        if (box) nodeLayouts[id] = box;
      }

      slices[laidOut.id] = {
        nodeLayouts,
        viewport: laidOut.viewport,
        handleOrder: extractHandleOrder(laidOut.snapshot.components),
      };
    }

    expect(Object.keys(slices)).toHaveLength(10);

    const outPath = resolve(import.meta.dirname, "layouts.generated.ts");
    writeFileSync(outPath, serializeLayouts(slices), "utf8");
  }, 60_000);
});
