/* eslint-disable */
/**
 * AUTO-GENERATED by generate-layouts.test.ts — do not edit by hand.
 * Regenerate: npx vitest run src/fixtures/seeds/pixledger/generate-layouts.test.ts
 */
import type { NodeLayout } from "@/features/diagram";

export interface SeedLaidOutSlice {
  nodeLayouts: Record<string, NodeLayout>;
  viewport: { x: number; y: number; zoom: number };
  handleOrder: Record<string, { outgoing: string[]; incoming: string[] }>;
}

export const SEED_PL_LAID_OUT: Record<string, SeedLaidOutSlice> = {
  "d-pl-context": {
    "nodeLayouts": {
      "pl-ctx-payer": {
        "elementId": "pl-ctx-payer",
        "x": 526,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-ctx-merchant": {
        "elementId": "pl-ctx-merchant",
        "x": 196,
        "y": 213.33333333333331,
        "width": 180,
        "height": 80
      },
      "pl-ctx-hub": {
        "elementId": "pl-ctx-hub",
        "x": 856,
        "y": 53.33333333333333,
        "width": 180,
        "height": 80
      },
      "pl-ctx-ledger": {
        "elementId": "pl-ctx-ledger",
        "x": 1186,
        "y": 249.99999999999997,
        "width": 180,
        "height": 80
      },
      "pl-ctx-risk": {
        "elementId": "pl-ctx-risk",
        "x": 1516,
        "y": 46.66666666666666,
        "width": 180,
        "height": 80
      },
      "pl-ctx-platform": {
        "elementId": "pl-ctx-platform",
        "x": 526,
        "y": 213.33333333333331,
        "width": 180,
        "height": 80
      },
      "pl-ctx-spi": {
        "elementId": "pl-ctx-spi",
        "x": 1186,
        "y": 84.33333333333333,
        "width": 180,
        "height": 80
      },
      "pl-ctx-bank": {
        "elementId": "pl-ctx-bank",
        "x": 1516,
        "y": 263.3333333333333,
        "width": 180,
        "height": 80
      },
      "pl-ctx-kyc": {
        "elementId": "pl-ctx-kyc",
        "x": 1846,
        "y": 46.66666666666666,
        "width": 180,
        "height": 80
      },
      "pl-ctx-notify": {
        "elementId": "pl-ctx-notify",
        "x": 856,
        "y": 213.33333333333331,
        "width": 180,
        "height": 80
      },
      "pl-ctx-note": {
        "elementId": "pl-ctx-note",
        "x": 40,
        "y": 373.3333333333333,
        "width": 336,
        "height": 475
      }
    },
    "viewport": {
      "x": 40,
      "y": 20,
      "zoom": 0.4738400789733465
    },
    "handleOrder": {
      "pl-ctx-payer": {
        "outgoing": [
          "pl-ctx-r1"
        ],
        "incoming": []
      },
      "pl-ctx-merchant": {
        "outgoing": [
          "pl-ctx-r2"
        ],
        "incoming": []
      },
      "pl-ctx-hub": {
        "outgoing": [
          "pl-ctx-r5",
          "pl-ctx-r4",
          "pl-ctx-r3"
        ],
        "incoming": [
          "pl-ctx-r1",
          "pl-ctx-r8"
        ]
      },
      "pl-ctx-ledger": {
        "outgoing": [
          "pl-ctx-r11",
          "pl-ctx-r6"
        ],
        "incoming": [
          "pl-ctx-r3",
          "pl-ctx-r9"
        ]
      },
      "pl-ctx-risk": {
        "outgoing": [
          "pl-ctx-r7"
        ],
        "incoming": [
          "pl-ctx-r5",
          "pl-ctx-r11"
        ]
      },
      "pl-ctx-platform": {
        "outgoing": [
          "pl-ctx-r8",
          "pl-ctx-r10",
          "pl-ctx-r9"
        ],
        "incoming": [
          "pl-ctx-r2"
        ]
      },
      "pl-ctx-spi": {
        "outgoing": [],
        "incoming": [
          "pl-ctx-r4"
        ]
      },
      "pl-ctx-bank": {
        "outgoing": [],
        "incoming": [
          "pl-ctx-r6"
        ]
      },
      "pl-ctx-kyc": {
        "outgoing": [],
        "incoming": [
          "pl-ctx-r7"
        ]
      },
      "pl-ctx-notify": {
        "outgoing": [],
        "incoming": [
          "pl-ctx-r10"
        ]
      }
    }
  },
  "d-pl-ct-hub": {
    "nodeLayouts": {
      "pl-hub-payer": {
        "elementId": "pl-hub-payer",
        "x": 196,
        "y": 595,
        "width": 180,
        "height": 80
      },
      "pl-hub-merchant-sys": {
        "elementId": "pl-hub-merchant-sys",
        "x": 526,
        "y": 1311.6666666666665,
        "width": 180,
        "height": 80
      },
      "pl-hub-boundary": {
        "elementId": "pl-hub-boundary",
        "x": 861,
        "y": 631.6666666666666,
        "width": 920,
        "height": 960
      },
      "pl-hub-cob-api": {
        "elementId": "pl-hub-cob-api",
        "x": 40,
        "y": 680,
        "width": 180,
        "height": 80
      },
      "pl-hub-dict": {
        "elementId": "pl-hub-dict",
        "x": 370,
        "y": 813.3333333333334,
        "width": 180,
        "height": 80
      },
      "pl-hub-webhook": {
        "elementId": "pl-hub-webhook",
        "x": 40,
        "y": 520,
        "width": 180,
        "height": 80
      },
      "pl-hub-cache": {
        "elementId": "pl-hub-cache",
        "x": 370,
        "y": 653.3333333333334,
        "width": 180,
        "height": 80
      },
      "pl-hub-queue": {
        "elementId": "pl-hub-queue",
        "x": 370,
        "y": 486.66666666666663,
        "width": 180,
        "height": 80
      },
      "pl-hub-worker": {
        "elementId": "pl-hub-worker",
        "x": 40,
        "y": 360,
        "width": 180,
        "height": 80
      },
      "pl-hub-spi": {
        "elementId": "pl-hub-spi",
        "x": 526,
        "y": 595,
        "width": 180,
        "height": 80
      },
      "pl-hub-risk-ext": {
        "elementId": "pl-hub-risk-ext",
        "x": 1936,
        "y": 1168.3333333333333,
        "width": 180,
        "height": 80
      },
      "pl-hub-ledger-ext": {
        "elementId": "pl-hub-ledger-ext",
        "x": 1936,
        "y": 978.3333333333333,
        "width": 180,
        "height": 80
      },
      "pl-hub-note": {
        "elementId": "pl-hub-note",
        "x": 40,
        "y": 40,
        "width": 336,
        "height": 475
      },
      "pl-hub-ep-post": {
        "elementId": "pl-hub-ep-post",
        "x": 40,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-hub-auth-guard": {
        "elementId": "pl-hub-auth-guard",
        "x": 370,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-hub-cob-svc": {
        "elementId": "pl-hub-cob-svc",
        "x": 700,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-hub-cache-svc": {
        "elementId": "pl-hub-cache-svc",
        "x": 40,
        "y": 200,
        "width": 180,
        "height": 80
      },
      "pl-hub-event-pub": {
        "elementId": "pl-hub-event-pub",
        "x": 40,
        "y": 840,
        "width": 180,
        "height": 80
      }
    },
    "viewport": {
      "x": 40,
      "y": 20,
      "zoom": 0.4020942408376964
    },
    "handleOrder": {
      "pl-hub-payer": {
        "outgoing": [
          "pl-hub-c-payer"
        ],
        "incoming": []
      },
      "pl-hub-merchant-sys": {
        "outgoing": [
          "pl-hub-c-merchant"
        ],
        "incoming": []
      },
      "pl-hub-cob-api": {
        "outgoing": [
          "pl-hub-c-cob-cache",
          "pl-hub-c-dict"
        ],
        "incoming": [
          "pl-hub-c-merchant"
        ]
      },
      "pl-hub-dict": {
        "outgoing": [
          "pl-hub-c-dict-spi"
        ],
        "incoming": [
          "pl-hub-c-dict"
        ]
      },
      "pl-hub-webhook": {
        "outgoing": [
          "pl-hub-c-queue",
          "pl-hub-c-risk",
          "pl-hub-c-cache"
        ],
        "incoming": [
          "pl-hub-c-spi"
        ]
      },
      "pl-hub-cache": {
        "outgoing": [],
        "incoming": [
          "pl-hub-c-cache",
          "pl-hub-c-cob-cache"
        ]
      },
      "pl-hub-queue": {
        "outgoing": [],
        "incoming": [
          "pl-hub-c-worker",
          "pl-hub-c-queue"
        ]
      },
      "pl-hub-worker": {
        "outgoing": [
          "pl-hub-c-ledger",
          "pl-hub-c-worker"
        ],
        "incoming": []
      },
      "pl-hub-spi": {
        "outgoing": [
          "pl-hub-c-spi"
        ],
        "incoming": [
          "pl-hub-c-dict-spi",
          "pl-hub-c-payer"
        ]
      },
      "pl-hub-risk-ext": {
        "outgoing": [],
        "incoming": [
          "pl-hub-c-risk"
        ]
      },
      "pl-hub-ledger-ext": {
        "outgoing": [],
        "incoming": [
          "pl-hub-c-ledger"
        ]
      },
      "pl-hub-ep-post": {
        "outgoing": [
          "pl-hub-c-ep-guard"
        ],
        "incoming": []
      },
      "pl-hub-auth-guard": {
        "outgoing": [
          "pl-hub-c-guard-svc"
        ],
        "incoming": [
          "pl-hub-c-ep-guard"
        ]
      },
      "pl-hub-cob-svc": {
        "outgoing": [],
        "incoming": [
          "pl-hub-c-guard-svc"
        ]
      }
    }
  },
  "d-pl-ct-ledger": {
    "nodeLayouts": {
      "pl-led-hub-ext": {
        "elementId": "pl-led-hub-ext",
        "x": 196,
        "y": 595,
        "width": 180,
        "height": 80
      },
      "pl-led-boundary": {
        "elementId": "pl-led-boundary",
        "x": 531,
        "y": 375,
        "width": 590,
        "height": 353.33333333333337
      },
      "pl-led-engine": {
        "elementId": "pl-led-engine",
        "x": 40,
        "y": 220,
        "width": 180,
        "height": 80
      },
      "pl-led-db": {
        "elementId": "pl-led-db",
        "x": 370,
        "y": 233.33333333333334,
        "width": 180,
        "height": 80
      },
      "pl-led-settlement": {
        "elementId": "pl-led-settlement",
        "x": 40,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-led-kafka": {
        "elementId": "pl-led-kafka",
        "x": 370,
        "y": 73.33333333333331,
        "width": 180,
        "height": 80
      },
      "pl-led-bank": {
        "elementId": "pl-led-bank",
        "x": 1276,
        "y": 386.3333333333333,
        "width": 180,
        "height": 80
      },
      "pl-led-risk": {
        "elementId": "pl-led-risk",
        "x": 1276,
        "y": 546.3333333333333,
        "width": 180,
        "height": 80
      },
      "pl-led-note": {
        "elementId": "pl-led-note",
        "x": 40,
        "y": 40,
        "width": 336,
        "height": 475
      }
    },
    "viewport": {
      "x": 40,
      "y": 20,
      "zoom": 0.6593406593406593
    },
    "handleOrder": {
      "pl-led-hub-ext": {
        "outgoing": [
          "pl-led-c1"
        ],
        "incoming": []
      },
      "pl-led-engine": {
        "outgoing": [
          "pl-led-c3",
          "pl-led-c2"
        ],
        "incoming": [
          "pl-led-c1"
        ]
      },
      "pl-led-db": {
        "outgoing": [],
        "incoming": [
          "pl-led-c2"
        ]
      },
      "pl-led-settlement": {
        "outgoing": [
          "pl-led-c5",
          "pl-led-c6",
          "pl-led-c4"
        ],
        "incoming": []
      },
      "pl-led-kafka": {
        "outgoing": [],
        "incoming": [
          "pl-led-c4",
          "pl-led-c3"
        ]
      },
      "pl-led-bank": {
        "outgoing": [],
        "incoming": [
          "pl-led-c5"
        ]
      },
      "pl-led-risk": {
        "outgoing": [],
        "incoming": [
          "pl-led-c6"
        ]
      }
    }
  },
  "d-pl-ct-risk": {
    "nodeLayouts": {
      "pl-risk-hub-ext": {
        "elementId": "pl-risk-hub-ext",
        "x": 196,
        "y": 801.6666666666667,
        "width": 180,
        "height": 80
      },
      "pl-risk-led-ext": {
        "elementId": "pl-risk-led-ext",
        "x": 196,
        "y": 86.66666666666667,
        "width": 180,
        "height": 80
      },
      "pl-risk-boundary": {
        "elementId": "pl-risk-boundary",
        "x": 531,
        "y": 40,
        "width": 920,
        "height": 331
      },
      "pl-risk-engine": {
        "elementId": "pl-risk-engine",
        "x": 370,
        "y": 60,
        "width": 180,
        "height": 80
      },
      "pl-risk-rules": {
        "elementId": "pl-risk-rules",
        "x": 700,
        "y": 200,
        "width": 180,
        "height": 80
      },
      "pl-risk-features": {
        "elementId": "pl-risk-features",
        "x": 700,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-risk-api": {
        "elementId": "pl-risk-api",
        "x": 40,
        "y": 60,
        "width": 180,
        "height": 80
      },
      "pl-risk-kyc": {
        "elementId": "pl-risk-kyc",
        "x": 1606,
        "y": 290,
        "width": 180,
        "height": 80
      },
      "pl-risk-note": {
        "elementId": "pl-risk-note",
        "x": 40,
        "y": 246.66666666666669,
        "width": 336,
        "height": 475
      }
    },
    "viewport": {
      "x": 40,
      "y": 20,
      "zoom": 0.5375139977603584
    },
    "handleOrder": {
      "pl-risk-hub-ext": {
        "outgoing": [
          "pl-risk-c1"
        ],
        "incoming": []
      },
      "pl-risk-led-ext": {
        "outgoing": [
          "pl-risk-c2"
        ],
        "incoming": []
      },
      "pl-risk-engine": {
        "outgoing": [
          "pl-risk-c5",
          "pl-risk-c4",
          "pl-risk-c6"
        ],
        "incoming": [
          "pl-risk-c3"
        ]
      },
      "pl-risk-rules": {
        "outgoing": [],
        "incoming": [
          "pl-risk-c4"
        ]
      },
      "pl-risk-features": {
        "outgoing": [],
        "incoming": [
          "pl-risk-c5"
        ]
      },
      "pl-risk-api": {
        "outgoing": [
          "pl-risk-c3"
        ],
        "incoming": [
          "pl-risk-c2",
          "pl-risk-c1"
        ]
      },
      "pl-risk-kyc": {
        "outgoing": [],
        "incoming": [
          "pl-risk-c6"
        ]
      }
    }
  },
  "d-pl-ct-merchant": {
    "nodeLayouts": {
      "pl-mer-user": {
        "elementId": "pl-mer-user",
        "x": 196,
        "y": 595,
        "width": 180,
        "height": 80
      },
      "pl-mer-boundary": {
        "elementId": "pl-mer-boundary",
        "x": 531,
        "y": 528.3333333333334,
        "width": 920,
        "height": 502
      },
      "pl-mer-spa": {
        "elementId": "pl-mer-spa",
        "x": 40,
        "y": 66.66666666666666,
        "width": 180,
        "height": 80
      },
      "pl-mer-api": {
        "elementId": "pl-mer-api",
        "x": 370,
        "y": 66.66666666666666,
        "width": 180,
        "height": 80
      },
      "pl-mer-webhooks": {
        "elementId": "pl-mer-webhooks",
        "x": 700,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-mer-db": {
        "elementId": "pl-mer-db",
        "x": 700,
        "y": 200,
        "width": 180,
        "height": 80
      },
      "pl-mer-notify": {
        "elementId": "pl-mer-notify",
        "x": 700,
        "y": 360,
        "width": 180,
        "height": 80
      },
      "pl-mer-hub": {
        "elementId": "pl-mer-hub",
        "x": 1606,
        "y": 789.3333333333334,
        "width": 180,
        "height": 80
      },
      "pl-mer-ledger": {
        "elementId": "pl-mer-ledger",
        "x": 1606,
        "y": 949.3333333333334,
        "width": 180,
        "height": 80
      },
      "pl-mer-sms": {
        "elementId": "pl-mer-sms",
        "x": 1606,
        "y": 629.3333333333334,
        "width": 180,
        "height": 80
      },
      "pl-mer-note": {
        "elementId": "pl-mer-note",
        "x": 40,
        "y": 40,
        "width": 336,
        "height": 475
      }
    },
    "viewport": {
      "x": 40,
      "y": 20,
      "zoom": 0.5375139977603584
    },
    "handleOrder": {
      "pl-mer-user": {
        "outgoing": [
          "pl-mer-c1"
        ],
        "incoming": []
      },
      "pl-mer-spa": {
        "outgoing": [
          "pl-mer-c2"
        ],
        "incoming": [
          "pl-mer-c1"
        ]
      },
      "pl-mer-api": {
        "outgoing": [
          "pl-mer-c6",
          "pl-mer-c5",
          "pl-mer-c7",
          "pl-mer-c3",
          "pl-mer-c4"
        ],
        "incoming": [
          "pl-mer-c2"
        ]
      },
      "pl-mer-webhooks": {
        "outgoing": [],
        "incoming": [
          "pl-mer-c6"
        ]
      },
      "pl-mer-db": {
        "outgoing": [],
        "incoming": [
          "pl-mer-c5"
        ]
      },
      "pl-mer-notify": {
        "outgoing": [
          "pl-mer-c8"
        ],
        "incoming": [
          "pl-mer-c7"
        ]
      },
      "pl-mer-hub": {
        "outgoing": [],
        "incoming": [
          "pl-mer-c3"
        ]
      },
      "pl-mer-ledger": {
        "outgoing": [],
        "incoming": [
          "pl-mer-c4"
        ]
      },
      "pl-mer-sms": {
        "outgoing": [],
        "incoming": [
          "pl-mer-c8"
        ]
      }
    }
  },
  "d-pl-dp-hub": {
    "nodeLayouts": {
      "pl-dph-vpc": {
        "elementId": "pl-dph-vpc",
        "x": 40,
        "y": 40,
        "width": 1680,
        "height": 725
      },
      "pl-dph-public": {
        "elementId": "pl-dph-public",
        "x": 40,
        "y": 40,
        "width": 710,
        "height": 428
      },
      "pl-dph-private": {
        "elementId": "pl-dph-private",
        "x": 910,
        "y": 58,
        "width": 260,
        "height": 320
      },
      "pl-dph-data": {
        "elementId": "pl-dph-data",
        "x": 1330,
        "y": 45,
        "width": 310,
        "height": 640
      },
      "pl-dph-apigw": {
        "elementId": "pl-dph-apigw",
        "x": 40,
        "y": 120,
        "width": 260,
        "height": 111
      },
      "pl-dph-api-group": {
        "elementId": "pl-dph-api-group",
        "x": -430,
        "y": 170,
        "width": 300,
        "height": 188
      },
      "pl-dph-ep-cob": {
        "elementId": "pl-dph-ep-cob",
        "x": 12,
        "y": 48,
        "width": 276,
        "height": 40
      },
      "pl-dph-ep-get": {
        "elementId": "pl-dph-ep-get",
        "x": 12,
        "y": 92,
        "width": 276,
        "height": 40
      },
      "pl-dph-lambda": {
        "elementId": "pl-dph-lambda",
        "x": 430,
        "y": 308,
        "width": 242,
        "height": 95
      },
      "pl-dph-ecs": {
        "elementId": "pl-dph-ecs",
        "x": 40,
        "y": 40,
        "width": 200,
        "height": 95
      },
      "pl-dph-worker": {
        "elementId": "pl-dph-worker",
        "x": 40,
        "y": 200,
        "width": 212,
        "height": 95
      },
      "pl-dph-ddb": {
        "elementId": "pl-dph-ddb",
        "x": 40,
        "y": 360,
        "width": 208,
        "height": 95
      },
      "pl-dph-redis": {
        "elementId": "pl-dph-redis",
        "x": 40,
        "y": 40,
        "width": 200,
        "height": 95
      },
      "pl-dph-sqs": {
        "elementId": "pl-dph-sqs",
        "x": 40,
        "y": 520,
        "width": 248,
        "height": 95
      },
      "pl-dph-cw": {
        "elementId": "pl-dph-cw",
        "x": 40,
        "y": 200,
        "width": 200,
        "height": 95
      }
    },
    "viewport": {
      "x": 328,
      "y": 217,
      "zoom": 0.64
    },
    "handleOrder": {
      "pl-dph-apigw": {
        "outgoing": [
          "pl-dph-c-routes",
          "pl-dph-c1",
          "pl-dph-c-proxy"
        ],
        "incoming": [
          "pl-dph-c-ep-cob",
          "pl-dph-c-ep-get"
        ]
      },
      "pl-dph-api-group": {
        "outgoing": [
          "pl-dph-c-http"
        ],
        "incoming": [
          "pl-dph-c-routes"
        ]
      },
      "pl-dph-ep-cob": {
        "outgoing": [
          "pl-dph-c-ep-cob"
        ],
        "incoming": []
      },
      "pl-dph-ep-get": {
        "outgoing": [
          "pl-dph-c-ep-get"
        ],
        "incoming": []
      },
      "pl-dph-lambda": {
        "outgoing": [
          "pl-dph-c3"
        ],
        "incoming": [
          "pl-dph-c1"
        ]
      },
      "pl-dph-ecs": {
        "outgoing": [
          "pl-dph-c5",
          "pl-dph-c4"
        ],
        "incoming": [
          "pl-dph-c-http",
          "pl-dph-c-proxy"
        ]
      },
      "pl-dph-worker": {
        "outgoing": [
          "pl-dph-c6"
        ],
        "incoming": []
      },
      "pl-dph-ddb": {
        "outgoing": [],
        "incoming": [
          "pl-dph-c4"
        ]
      },
      "pl-dph-redis": {
        "outgoing": [],
        "incoming": [
          "pl-dph-c5"
        ]
      },
      "pl-dph-sqs": {
        "outgoing": [],
        "incoming": [
          "pl-dph-c6",
          "pl-dph-c3"
        ]
      }
    }
  },
  "d-pl-dp-ledger": {
    "nodeLayouts": {
      "pl-dpl-vpc": {
        "elementId": "pl-dpl-vpc",
        "x": 40,
        "y": 40,
        "width": 760,
        "height": 720
      },
      "pl-dpl-private": {
        "elementId": "pl-dpl-private",
        "x": 40,
        "y": 53.33333333333333,
        "width": 260,
        "height": 320
      },
      "pl-dpl-data": {
        "elementId": "pl-dpl-data",
        "x": 460,
        "y": 40,
        "width": 260,
        "height": 640
      },
      "pl-dpl-ecs": {
        "elementId": "pl-dpl-ecs",
        "x": 40,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-dpl-settle": {
        "elementId": "pl-dpl-settle",
        "x": 40,
        "y": 200,
        "width": 180,
        "height": 80
      },
      "pl-dpl-aurora": {
        "elementId": "pl-dpl-aurora",
        "x": 40,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-dpl-msk": {
        "elementId": "pl-dpl-msk",
        "x": 40,
        "y": 200,
        "width": 180,
        "height": 80
      },
      "pl-dpl-sqs": {
        "elementId": "pl-dpl-sqs",
        "x": 40,
        "y": 360,
        "width": 180,
        "height": 80
      },
      "pl-dpl-s3": {
        "elementId": "pl-dpl-s3",
        "x": 40,
        "y": 520,
        "width": 180,
        "height": 80
      }
    },
    "viewport": {
      "x": 40,
      "y": 20,
      "zoom": 0.8
    },
    "handleOrder": {
      "pl-dpl-ecs": {
        "outgoing": [
          "pl-dpl-c1",
          "pl-dpl-c2"
        ],
        "incoming": []
      },
      "pl-dpl-settle": {
        "outgoing": [
          "pl-dpl-c3",
          "pl-dpl-c5",
          "pl-dpl-c4"
        ],
        "incoming": []
      },
      "pl-dpl-aurora": {
        "outgoing": [],
        "incoming": [
          "pl-dpl-c1"
        ]
      },
      "pl-dpl-msk": {
        "outgoing": [],
        "incoming": [
          "pl-dpl-c2",
          "pl-dpl-c3"
        ]
      },
      "pl-dpl-sqs": {
        "outgoing": [],
        "incoming": [
          "pl-dpl-c5"
        ]
      },
      "pl-dpl-s3": {
        "outgoing": [],
        "incoming": [
          "pl-dpl-c4"
        ]
      }
    }
  },
  "d-pl-dp-risk": {
    "nodeLayouts": {
      "pl-dpr-cluster": {
        "elementId": "pl-dpr-cluster",
        "x": 40,
        "y": 40,
        "width": 1580,
        "height": 640
      },
      "pl-dpr-ingress": {
        "elementId": "pl-dpr-ingress",
        "x": 40,
        "y": 64,
        "width": 180,
        "height": 80
      },
      "pl-dpr-svc": {
        "elementId": "pl-dpr-svc",
        "x": 370,
        "y": 64,
        "width": 180,
        "height": 80
      },
      "pl-dpr-deploy": {
        "elementId": "pl-dpr-deploy",
        "x": 1030,
        "y": 64,
        "width": 180,
        "height": 80
      },
      "pl-dpr-api-deploy": {
        "elementId": "pl-dpr-api-deploy",
        "x": 700,
        "y": 64,
        "width": 180,
        "height": 80
      },
      "pl-dpr-cm": {
        "elementId": "pl-dpr-cm",
        "x": 1360,
        "y": 200,
        "width": 180,
        "height": 80
      },
      "pl-dpr-secret": {
        "elementId": "pl-dpr-secret",
        "x": 1360,
        "y": 360,
        "width": 180,
        "height": 80
      },
      "pl-dpr-pvc": {
        "elementId": "pl-dpr-pvc",
        "x": 1360,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-dpr-redis": {
        "elementId": "pl-dpr-redis",
        "x": 1360,
        "y": 520,
        "width": 180,
        "height": 80
      }
    },
    "viewport": {
      "x": 40,
      "y": 20,
      "zoom": 0.5925925925925926
    },
    "handleOrder": {
      "pl-dpr-ingress": {
        "outgoing": [
          "pl-dpr-c1"
        ],
        "incoming": []
      },
      "pl-dpr-svc": {
        "outgoing": [
          "pl-dpr-c2"
        ],
        "incoming": [
          "pl-dpr-c1"
        ]
      },
      "pl-dpr-deploy": {
        "outgoing": [
          "pl-dpr-c6",
          "pl-dpr-c4",
          "pl-dpr-c5",
          "pl-dpr-c7"
        ],
        "incoming": [
          "pl-dpr-c3"
        ]
      },
      "pl-dpr-api-deploy": {
        "outgoing": [
          "pl-dpr-c3"
        ],
        "incoming": [
          "pl-dpr-c2"
        ]
      },
      "pl-dpr-cm": {
        "outgoing": [],
        "incoming": [
          "pl-dpr-c4"
        ]
      },
      "pl-dpr-secret": {
        "outgoing": [],
        "incoming": [
          "pl-dpr-c5"
        ]
      },
      "pl-dpr-pvc": {
        "outgoing": [],
        "incoming": [
          "pl-dpr-c6"
        ]
      },
      "pl-dpr-redis": {
        "outgoing": [],
        "incoming": [
          "pl-dpr-c7"
        ]
      }
    }
  },
  "d-pl-dp-merchant": {
    "nodeLayouts": {
      "pl-dpm-edge": {
        "elementId": "pl-dpm-edge",
        "x": 335,
        "y": 40,
        "width": 590,
        "height": 160
      },
      "pl-dpm-cf": {
        "elementId": "pl-dpm-cf",
        "x": 40,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-dpm-s3": {
        "elementId": "pl-dpm-s3",
        "x": 370,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-dpm-vpc": {
        "elementId": "pl-dpm-vpc",
        "x": 40,
        "y": 280,
        "width": 1180,
        "height": 560
      },
      "pl-dpm-public": {
        "elementId": "pl-dpm-public",
        "x": 40,
        "y": 340,
        "width": 260,
        "height": 160
      },
      "pl-dpm-private": {
        "elementId": "pl-dpm-private",
        "x": 460,
        "y": 180,
        "width": 260,
        "height": 320
      },
      "pl-dpm-data": {
        "elementId": "pl-dpm-data",
        "x": 880,
        "y": 40,
        "width": 260,
        "height": 480
      },
      "pl-dpm-elb": {
        "elementId": "pl-dpm-elb",
        "x": 40,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-dpm-ecs": {
        "elementId": "pl-dpm-ecs",
        "x": 40,
        "y": 200,
        "width": 180,
        "height": 80
      },
      "pl-dpm-wh": {
        "elementId": "pl-dpm-wh",
        "x": 40,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-dpm-rds": {
        "elementId": "pl-dpm-rds",
        "x": 40,
        "y": 200,
        "width": 180,
        "height": 80
      },
      "pl-dpm-redis": {
        "elementId": "pl-dpm-redis",
        "x": 40,
        "y": 360,
        "width": 180,
        "height": 80
      },
      "pl-dpm-sqs": {
        "elementId": "pl-dpm-sqs",
        "x": 40,
        "y": 40,
        "width": 180,
        "height": 80
      }
    },
    "viewport": {
      "x": 40,
      "y": 20,
      "zoom": 0.7619047619047619
    },
    "handleOrder": {
      "pl-dpm-cf": {
        "outgoing": [
          "pl-dpm-c1"
        ],
        "incoming": []
      },
      "pl-dpm-s3": {
        "outgoing": [],
        "incoming": [
          "pl-dpm-c1"
        ]
      },
      "pl-dpm-elb": {
        "outgoing": [
          "pl-dpm-c2"
        ],
        "incoming": []
      },
      "pl-dpm-ecs": {
        "outgoing": [
          "pl-dpm-c5",
          "pl-dpm-c3",
          "pl-dpm-c4"
        ],
        "incoming": [
          "pl-dpm-c2"
        ]
      },
      "pl-dpm-wh": {
        "outgoing": [
          "pl-dpm-c6"
        ],
        "incoming": []
      },
      "pl-dpm-rds": {
        "outgoing": [],
        "incoming": [
          "pl-dpm-c3"
        ]
      },
      "pl-dpm-redis": {
        "outgoing": [],
        "incoming": [
          "pl-dpm-c4"
        ]
      },
      "pl-dpm-sqs": {
        "outgoing": [],
        "incoming": [
          "pl-dpm-c6",
          "pl-dpm-c5"
        ]
      }
    }
  },
  "d-pl-catalog": {
    "nodeLayouts": {
      "pl-cat-c4": {
        "elementId": "pl-cat-c4",
        "x": 250,
        "y": 40,
        "width": 260,
        "height": 640
      },
      "pl-cat-person": {
        "elementId": "pl-cat-person",
        "x": 40,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-cat-system": {
        "elementId": "pl-cat-system",
        "x": 40,
        "y": 520,
        "width": 180,
        "height": 80
      },
      "pl-cat-container": {
        "elementId": "pl-cat-container",
        "x": 40,
        "y": 360,
        "width": 180,
        "height": 80
      },
      "pl-cat-component": {
        "elementId": "pl-cat-component",
        "x": 40,
        "y": 200,
        "width": 180,
        "height": 80
      },
      "pl-cat-aws": {
        "elementId": "pl-cat-aws",
        "x": 250,
        "y": 5839,
        "width": 260,
        "height": 1440
      },
      "pl-cat-aws-lambda": {
        "elementId": "pl-cat-aws-lambda",
        "x": 40,
        "y": 1160,
        "width": 180,
        "height": 80
      },
      "pl-cat-aws-s3": {
        "elementId": "pl-cat-aws-s3",
        "x": 40,
        "y": 520,
        "width": 180,
        "height": 80
      },
      "pl-cat-aws-rds": {
        "elementId": "pl-cat-aws-rds",
        "x": 40,
        "y": 360,
        "width": 180,
        "height": 80
      },
      "pl-cat-aws-vpc": {
        "elementId": "pl-cat-aws-vpc",
        "x": 40,
        "y": 1320,
        "width": 180,
        "height": 80
      },
      "pl-cat-aws-iam": {
        "elementId": "pl-cat-aws-iam",
        "x": 40,
        "y": 1000,
        "width": 180,
        "height": 80
      },
      "pl-cat-aws-athena": {
        "elementId": "pl-cat-aws-athena",
        "x": 40,
        "y": 200,
        "width": 180,
        "height": 80
      },
      "pl-cat-aws-sqs": {
        "elementId": "pl-cat-aws-sqs",
        "x": 40,
        "y": 840,
        "width": 180,
        "height": 80
      },
      "pl-cat-aws-ecr": {
        "elementId": "pl-cat-aws-ecr",
        "x": 40,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-cat-aws-cw": {
        "elementId": "pl-cat-aws-cw",
        "x": 40,
        "y": 680,
        "width": 180,
        "height": 80
      },
      "pl-cat-gcp": {
        "elementId": "pl-cat-gcp",
        "x": 250,
        "y": 760,
        "width": 260,
        "height": 1280
      },
      "pl-cat-gcp-run": {
        "elementId": "pl-cat-gcp-run",
        "x": 40,
        "y": 360,
        "width": 180,
        "height": 80
      },
      "pl-cat-gcp-gcs": {
        "elementId": "pl-cat-gcp-gcs",
        "x": 40,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-cat-gcp-sql": {
        "elementId": "pl-cat-gcp-sql",
        "x": 40,
        "y": 840,
        "width": 180,
        "height": 80
      },
      "pl-cat-gcp-net": {
        "elementId": "pl-cat-gcp-net",
        "x": 40,
        "y": 1160,
        "width": 180,
        "height": 80
      },
      "pl-cat-gcp-sec": {
        "elementId": "pl-cat-gcp-sec",
        "x": 40,
        "y": 520,
        "width": 180,
        "height": 80
      },
      "pl-cat-gcp-bq": {
        "elementId": "pl-cat-gcp-bq",
        "x": 40,
        "y": 680,
        "width": 180,
        "height": 80
      },
      "pl-cat-gcp-ai": {
        "elementId": "pl-cat-gcp-ai",
        "x": 40,
        "y": 200,
        "width": 180,
        "height": 80
      },
      "pl-cat-gcp-int": {
        "elementId": "pl-cat-gcp-int",
        "x": 40,
        "y": 1000,
        "width": 180,
        "height": 80
      },
      "pl-cat-azure": {
        "elementId": "pl-cat-azure",
        "x": 250,
        "y": 7359,
        "width": 260,
        "height": 1120
      },
      "pl-cat-az-fn": {
        "elementId": "pl-cat-az-fn",
        "x": 40,
        "y": 840,
        "width": 180,
        "height": 80
      },
      "pl-cat-az-blob": {
        "elementId": "pl-cat-az-blob",
        "x": 40,
        "y": 200,
        "width": 180,
        "height": 80
      },
      "pl-cat-az-cosmos": {
        "elementId": "pl-cat-az-cosmos",
        "x": 40,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-cat-az-vnet": {
        "elementId": "pl-cat-az-vnet",
        "x": 40,
        "y": 520,
        "width": 180,
        "height": 80
      },
      "pl-cat-az-kv": {
        "elementId": "pl-cat-az-kv",
        "x": 40,
        "y": 1000,
        "width": 180,
        "height": 80
      },
      "pl-cat-az-sa": {
        "elementId": "pl-cat-az-sa",
        "x": 40,
        "y": 360,
        "width": 180,
        "height": 80
      },
      "pl-cat-az-bus": {
        "elementId": "pl-cat-az-bus",
        "x": 40,
        "y": 680,
        "width": 180,
        "height": 80
      },
      "pl-cat-k8s": {
        "elementId": "pl-cat-k8s",
        "x": 250,
        "y": 4719,
        "width": 260,
        "height": 640
      },
      "pl-cat-k8s-deploy": {
        "elementId": "pl-cat-k8s-deploy",
        "x": 40,
        "y": 360,
        "width": 180,
        "height": 80
      },
      "pl-cat-k8s-ing": {
        "elementId": "pl-cat-k8s-ing",
        "x": 40,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-cat-k8s-pvc": {
        "elementId": "pl-cat-k8s-pvc",
        "x": 40,
        "y": 520,
        "width": 180,
        "height": 80
      },
      "pl-cat-k8s-cm": {
        "elementId": "pl-cat-k8s-cm",
        "x": 40,
        "y": 200,
        "width": 180,
        "height": 80
      },
      "pl-cat-oss": {
        "elementId": "pl-cat-oss",
        "x": 250,
        "y": 5439,
        "width": 260,
        "height": 320
      },
      "pl-cat-oss-redis": {
        "elementId": "pl-cat-oss-redis",
        "x": 40,
        "y": 200,
        "width": 180,
        "height": 80
      },
      "pl-cat-oss-kafka": {
        "elementId": "pl-cat-oss-kafka",
        "x": 40,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-cat-struct": {
        "elementId": "pl-cat-struct",
        "x": 40,
        "y": 2120,
        "width": 680,
        "height": 2519
      },
      "pl-cat-note": {
        "elementId": "pl-cat-note",
        "x": 172,
        "y": 1844,
        "width": 336,
        "height": 475
      },
      "pl-cat-db": {
        "elementId": "pl-cat-db",
        "x": 137,
        "y": 1068,
        "width": 406,
        "height": 196
      },
      "pl-cat-json": {
        "elementId": "pl-cat-json",
        "x": 200,
        "y": 1584,
        "width": 280,
        "height": 180
      },
      "pl-cat-api": {
        "elementId": "pl-cat-api",
        "x": 190,
        "y": 200,
        "width": 300,
        "height": 148
      },
      "pl-cat-ep": {
        "elementId": "pl-cat-ep",
        "x": 1064,
        "y": 56,
        "width": 276,
        "height": 40
      },
      "pl-cat-panel": {
        "elementId": "pl-cat-panel",
        "x": 40,
        "y": 428,
        "width": 600,
        "height": 400
      },
      "pl-cat-process": {
        "elementId": "pl-cat-process",
        "x": 250,
        "y": 908,
        "width": 180,
        "height": 80
      },
      "pl-cat-ext": {
        "elementId": "pl-cat-ext",
        "x": 250,
        "y": 40,
        "width": 180,
        "height": 80
      },
      "pl-cat-svg": {
        "elementId": "pl-cat-svg",
        "x": 260,
        "y": 1344,
        "width": 160,
        "height": 160
      },
      "pl-cat-unknown": {
        "elementId": "pl-cat-unknown",
        "x": 250,
        "y": 2399,
        "width": 180,
        "height": 80
      }
    },
    "viewport": {
      "x": 40,
      "y": 20,
      "zoom": 0.35
    },
    "handleOrder": {}
  }
};
