import type { DiagramIR } from "@/features/llm/ir/ir.types";

/**
 * The four reference diagrams the layout configuration is measured against.
 *
 * These are hand-written IR documents matching the shapes the product owner
 * reviewed (C4 e-commerce, AWS ECS Fargate, C4 Context healthcare, AWS
 * microservices) — the IR of the reviewed generations was not kept, so these
 * are reconstructions, not captures. They are what the numbers in the spec's
 * readability metric refer to, so changing one invalidates the baseline.
 *
 * `ir-prompt.test.ts` style guarantee: every document here is validated by
 * `layoutReadability.baseline.test.ts` before it is measured, so a malformed
 * fixture fails loudly rather than skewing a number.
 */

/** C4 Container level: storefront, services, datastores, external systems. */
const c4Ecommerce: DiagramIR = {
  type: "c4-container",
  nodes: [
    { id: "customer", semanticType: "person", name: "Customer", parentId: null, tier: "external" },
    {
      id: "ops-staff",
      semanticType: "person",
      name: "Operations Staff",
      parentId: null,
      tier: "external",
    },
    {
      id: "shop",
      semanticType: "container",
      name: "E-commerce Platform",
      parentId: null,
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "web-app",
      semanticType: "container",
      name: "Web Storefront",
      technology: "Next.js",
      parentId: "shop",
      tier: "edge",
    },
    {
      id: "mobile-app",
      semanticType: "container",
      name: "Mobile App",
      technology: "React Native",
      parentId: "shop",
      tier: "edge",
    },
    {
      id: "api-gateway",
      semanticType: "container",
      name: "API Gateway",
      technology: "Kong",
      parentId: "shop",
      tier: "ingress",
    },
    {
      id: "catalog-svc",
      semanticType: "container",
      name: "Catalog Service",
      technology: "Go",
      parentId: "shop",
      tier: "compute",
    },
    {
      id: "cart-svc",
      semanticType: "container",
      name: "Cart Service",
      technology: "Node.js",
      parentId: "shop",
      tier: "compute",
    },
    {
      id: "order-svc",
      semanticType: "container",
      name: "Order Service",
      technology: "Java",
      parentId: "shop",
      tier: "compute",
    },
    {
      id: "admin-svc",
      semanticType: "container",
      name: "Admin Backoffice",
      technology: "Rails",
      parentId: "shop",
      tier: "compute",
    },
    {
      id: "catalog-db",
      semanticType: "database",
      name: "Catalog DB",
      technology: "PostgreSQL",
      parentId: "shop",
      tier: "data",
    },
    {
      id: "order-db",
      semanticType: "database",
      name: "Order DB",
      technology: "PostgreSQL",
      parentId: "shop",
      tier: "data",
    },
    {
      id: "cart-cache",
      semanticType: "database",
      name: "Cart Cache",
      technology: "Redis",
      parentId: "shop",
      tier: "data",
    },
    {
      id: "payment-gw",
      semanticType: "external-system",
      name: "Payment Gateway",
      parentId: null,
      tier: "integration",
    },
    {
      id: "shipping",
      semanticType: "external-system",
      name: "Shipping Provider",
      parentId: null,
      tier: "integration",
    },
    {
      id: "email",
      semanticType: "external-system",
      name: "Email Provider",
      parentId: null,
      tier: "integration",
    },
  ],
  edges: [
    { id: "e1", sourceId: "customer", targetId: "web-app", label: "browses" },
    { id: "e2", sourceId: "customer", targetId: "mobile-app", label: "browses" },
    { id: "e3", sourceId: "ops-staff", targetId: "admin-svc", label: "manages" },
    { id: "e4", sourceId: "web-app", targetId: "api-gateway", label: "HTTPS" },
    { id: "e5", sourceId: "mobile-app", targetId: "api-gateway", label: "HTTPS" },
    { id: "e6", sourceId: "api-gateway", targetId: "catalog-svc", label: "routes" },
    { id: "e7", sourceId: "api-gateway", targetId: "cart-svc", label: "routes" },
    { id: "e8", sourceId: "api-gateway", targetId: "order-svc", label: "routes" },
    { id: "e9", sourceId: "catalog-svc", targetId: "catalog-db", label: "reads/writes" },
    { id: "e10", sourceId: "cart-svc", targetId: "cart-cache", label: "reads/writes" },
    { id: "e11", sourceId: "order-svc", targetId: "order-db", label: "reads/writes" },
    { id: "e12", sourceId: "order-svc", targetId: "payment-gw", label: "charges" },
    { id: "e13", sourceId: "order-svc", targetId: "shipping", label: "books" },
    { id: "e14", sourceId: "order-svc", targetId: "email", label: "notifies" },
    { id: "e15", sourceId: "admin-svc", targetId: "catalog-db", label: "reads/writes" },
    { id: "e16", sourceId: "cart-svc", targetId: "catalog-svc", label: "prices" },
  ],
};

/** AWS deployment: ECS Fargate behind an ALB, two AZs, RDS Multi-AZ. */
const awsEcsFargate: DiagramIR = {
  type: "aws-deployment",
  nodes: [
    { id: "user", semanticType: "person", name: "End User", parentId: null, tier: "external" },
    {
      id: "cdn",
      semanticType: "aws-networking",
      name: "CloudFront",
      awsService: "cloudfront",
      parentId: null,
      tier: "edge",
    },
    {
      id: "vpc",
      semanticType: "aws-vpc",
      name: "Production",
      awsService: "vpc",
      parentId: null,
      isBoundary: true,
      tier: "edge",
    },
    {
      id: "az-a",
      semanticType: "aws-az",
      name: "us-east-1a",
      parentId: "vpc",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "az-b",
      semanticType: "aws-az",
      name: "us-east-1b",
      parentId: "vpc",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "pub-a",
      semanticType: "aws-public-subnet",
      name: "Public A",
      awsService: "public-subnet",
      parentId: "az-a",
      isBoundary: true,
      tier: "edge",
    },
    {
      id: "pub-b",
      semanticType: "aws-public-subnet",
      name: "Public B",
      awsService: "public-subnet",
      parentId: "az-b",
      isBoundary: true,
      tier: "edge",
    },
    {
      id: "priv-a",
      semanticType: "aws-private-subnet",
      name: "Private A",
      awsService: "private-subnet",
      parentId: "az-a",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "priv-b",
      semanticType: "aws-private-subnet",
      name: "Private B",
      awsService: "private-subnet",
      parentId: "az-b",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "alb",
      semanticType: "aws-networking",
      name: "Application Load Balancer",
      awsService: "elb",
      parentId: "pub-a",
      tier: "edge",
    },
    {
      id: "nat",
      semanticType: "aws-networking",
      name: "NAT Gateway",
      awsService: "vpc",
      parentId: "pub-b",
      tier: "ingress",
    },
    {
      id: "svc-a",
      semanticType: "aws-compute",
      name: "Orders Task",
      awsService: "fargate",
      technology: "Fargate",
      parentId: "priv-a",
      tier: "compute",
    },
    {
      id: "svc-b",
      semanticType: "aws-compute",
      name: "Orders Task (replica)",
      awsService: "fargate",
      technology: "Fargate",
      parentId: "priv-b",
      tier: "compute",
    },
    {
      id: "rds-primary",
      semanticType: "aws-database",
      name: "Orders DB (primary)",
      awsService: "rds",
      technology: "Aurora PostgreSQL",
      parentId: "priv-a",
      tier: "data",
    },
    {
      id: "rds-standby",
      semanticType: "aws-database",
      name: "Orders DB (standby)",
      awsService: "rds",
      technology: "Aurora PostgreSQL",
      parentId: "priv-b",
      tier: "data",
    },
    {
      id: "s3",
      semanticType: "aws-storage",
      name: "Assets Bucket",
      awsService: "s3",
      parentId: "vpc",
      tier: "data",
    },
    {
      id: "secrets",
      semanticType: "aws-security",
      name: "Secrets Manager",
      awsService: "secrets-manager",
      parentId: "vpc",
      tier: "integration",
    },
    {
      id: "logs",
      semanticType: "aws-management",
      name: "CloudWatch Logs",
      awsService: "cloudwatch",
      parentId: "vpc",
      tier: "integration",
    },
  ],
  edges: [
    { id: "a1", sourceId: "user", targetId: "cdn", label: "HTTPS" },
    { id: "a2", sourceId: "cdn", targetId: "alb", label: "origin" },
    { id: "a3", sourceId: "cdn", targetId: "s3", label: "static assets" },
    { id: "a4", sourceId: "alb", targetId: "svc-a", label: "forwards" },
    { id: "a5", sourceId: "alb", targetId: "svc-b", label: "forwards" },
    { id: "a6", sourceId: "svc-a", targetId: "rds-primary", label: "reads/writes" },
    { id: "a7", sourceId: "svc-b", targetId: "rds-primary", label: "reads/writes" },
    { id: "a8", sourceId: "rds-primary", targetId: "rds-standby", label: "replicates" },
    { id: "a9", sourceId: "svc-a", targetId: "secrets", label: "reads" },
    { id: "a10", sourceId: "svc-b", targetId: "secrets", label: "reads" },
    { id: "a11", sourceId: "svc-a", targetId: "logs", label: "ships logs" },
    { id: "a12", sourceId: "svc-b", targetId: "logs", label: "ships logs" },
    { id: "a13", sourceId: "svc-a", targetId: "nat", label: "egress" },
    { id: "a14", sourceId: "svc-b", targetId: "nat", label: "egress" },
  ],
};

/** C4 Context level: a healthcare system and everything it talks to. Flat. */
const c4ContextHealthcare: DiagramIR = {
  type: "c4-context",
  nodes: [
    { id: "patient", semanticType: "person", name: "Patient", parentId: null, tier: "external" },
    {
      id: "clinician",
      semanticType: "person",
      name: "Clinician",
      parentId: null,
      tier: "external",
    },
    {
      id: "admin",
      semanticType: "person",
      name: "Practice Administrator",
      parentId: null,
      tier: "external",
    },
    {
      id: "ehr",
      semanticType: "container",
      name: "Care Coordination Platform",
      parentId: null,
      tier: "compute",
    },
    {
      id: "hospital-his",
      semanticType: "external-system",
      name: "Hospital HIS",
      parentId: null,
      tier: "integration",
    },
    {
      id: "lab",
      semanticType: "external-system",
      name: "Laboratory System",
      parentId: null,
      tier: "integration",
    },
    {
      id: "pharmacy",
      semanticType: "external-system",
      name: "Pharmacy Network",
      parentId: null,
      tier: "integration",
    },
    {
      id: "insurer",
      semanticType: "external-system",
      name: "Insurance Clearinghouse",
      parentId: null,
      tier: "integration",
    },
    {
      id: "identity",
      semanticType: "external-system",
      name: "National Identity Service",
      parentId: null,
      tier: "integration",
    },
    {
      id: "sms",
      semanticType: "external-system",
      name: "SMS Provider",
      parentId: null,
      tier: "integration",
    },
  ],
  edges: [
    { id: "h1", sourceId: "patient", targetId: "ehr", label: "books appointments" },
    { id: "h2", sourceId: "clinician", targetId: "ehr", label: "records care" },
    { id: "h3", sourceId: "admin", targetId: "ehr", label: "administers" },
    { id: "h4", sourceId: "ehr", targetId: "hospital-his", label: "HL7 v2" },
    { id: "h5", sourceId: "ehr", targetId: "lab", label: "orders tests" },
    { id: "h6", sourceId: "lab", targetId: "ehr", label: "returns results" },
    { id: "h7", sourceId: "ehr", targetId: "pharmacy", label: "sends prescriptions" },
    { id: "h8", sourceId: "ehr", targetId: "insurer", label: "submits claims" },
    { id: "h9", sourceId: "ehr", targetId: "identity", label: "verifies identity" },
    { id: "h10", sourceId: "ehr", targetId: "sms", label: "sends reminders" },
    { id: "h11", sourceId: "patient", targetId: "identity", label: "authenticates" },
  ],
};

/** AWS microservices: event-driven, several compute styles, shared data tier. */
const awsMicroservices: DiagramIR = {
  type: "aws-deployment",
  nodes: [
    { id: "client", semanticType: "person", name: "Client", parentId: null, tier: "external" },
    {
      id: "vpc",
      semanticType: "aws-vpc",
      name: "Microservices",
      awsService: "vpc",
      parentId: null,
      isBoundary: true,
      tier: "edge",
    },
    {
      id: "apigw",
      semanticType: "aws-networking",
      name: "API Gateway",
      awsService: "api-gateway",
      parentId: "vpc",
      tier: "edge",
    },
    {
      id: "cognito",
      semanticType: "aws-security",
      name: "Cognito",
      awsService: "cognito",
      parentId: "vpc",
      tier: "edge",
    },
    {
      id: "priv",
      semanticType: "aws-private-subnet",
      name: "Private",
      awsService: "private-subnet",
      parentId: "vpc",
      isBoundary: true,
      tier: "compute",
    },
    {
      id: "orders-fn",
      semanticType: "aws-compute",
      name: "Orders",
      awsService: "lambda",
      technology: "Node.js",
      parentId: "priv",
      tier: "compute",
    },
    {
      id: "billing-fn",
      semanticType: "aws-compute",
      name: "Billing",
      awsService: "lambda",
      technology: "Python",
      parentId: "priv",
      tier: "compute",
    },
    {
      id: "inventory-fn",
      semanticType: "aws-compute",
      name: "Inventory",
      awsService: "lambda",
      technology: "Go",
      parentId: "priv",
      tier: "compute",
    },
    {
      id: "notify-fn",
      semanticType: "aws-compute",
      name: "Notifications",
      awsService: "lambda",
      technology: "Node.js",
      parentId: "priv",
      tier: "compute",
    },
    {
      id: "reporting",
      semanticType: "aws-compute",
      name: "Reporting Worker",
      awsService: "ecs",
      technology: "ECS",
      parentId: "priv",
      tier: "compute",
    },
    {
      id: "bus",
      semanticType: "aws-integration",
      name: "EventBridge",
      awsService: "eventbridge",
      parentId: "vpc",
      tier: "integration",
    },
    {
      id: "queue",
      semanticType: "aws-integration",
      name: "Billing Queue",
      awsService: "sqs",
      parentId: "vpc",
      tier: "integration",
    },
    {
      id: "topic",
      semanticType: "aws-integration",
      name: "Notifications Topic",
      awsService: "sns",
      parentId: "vpc",
      tier: "integration",
    },
    {
      id: "orders-table",
      semanticType: "aws-database",
      name: "Orders Table",
      awsService: "dynamodb",
      parentId: "vpc",
      tier: "data",
    },
    {
      id: "inventory-table",
      semanticType: "aws-database",
      name: "Inventory Table",
      awsService: "dynamodb",
      parentId: "vpc",
      tier: "data",
    },
    {
      id: "billing-db",
      semanticType: "aws-database",
      name: "Billing DB",
      awsService: "rds",
      technology: "PostgreSQL",
      parentId: "vpc",
      tier: "data",
    },
    {
      id: "reports-bucket",
      semanticType: "aws-storage",
      name: "Reports Bucket",
      awsService: "s3",
      parentId: "vpc",
      tier: "data",
    },
  ],
  edges: [
    { id: "m1", sourceId: "client", targetId: "apigw", label: "HTTPS" },
    { id: "m2", sourceId: "apigw", targetId: "cognito", label: "authorizes" },
    { id: "m3", sourceId: "apigw", targetId: "orders-fn", label: "invokes" },
    { id: "m4", sourceId: "apigw", targetId: "inventory-fn", label: "invokes" },
    { id: "m5", sourceId: "orders-fn", targetId: "orders-table", label: "reads/writes" },
    { id: "m6", sourceId: "orders-fn", targetId: "bus", label: "publishes" },
    { id: "m7", sourceId: "bus", targetId: "queue", label: "routes" },
    { id: "m8", sourceId: "bus", targetId: "topic", label: "routes" },
    { id: "m9", sourceId: "queue", targetId: "billing-fn", label: "triggers" },
    { id: "m10", sourceId: "topic", targetId: "notify-fn", label: "triggers" },
    { id: "m11", sourceId: "billing-fn", targetId: "billing-db", label: "reads/writes" },
    { id: "m12", sourceId: "inventory-fn", targetId: "inventory-table", label: "reads/writes" },
    { id: "m13", sourceId: "inventory-fn", targetId: "bus", label: "publishes" },
    { id: "m14", sourceId: "reporting", targetId: "orders-table", label: "scans" },
    { id: "m15", sourceId: "reporting", targetId: "billing-db", label: "reads" },
    { id: "m16", sourceId: "reporting", targetId: "reports-bucket", label: "writes" },
    { id: "m17", sourceId: "bus", targetId: "reporting", label: "schedules" },
  ],
};

export interface ReferenceDiagram {
  name: string;
  ir: DiagramIR;
}

export const REFERENCE_DIAGRAMS: ReferenceDiagram[] = [
  { name: "C4 e-commerce", ir: c4Ecommerce },
  { name: "AWS ECS Fargate", ir: awsEcsFargate },
  { name: "C4 Context healthcare", ir: c4ContextHealthcare },
  { name: "AWS microservices", ir: awsMicroservices },
];

/** Edge id -> label, for sizing the estimated label boxes when measuring. */
export function labelsOf(ir: DiagramIR): Map<string, string> {
  return new Map(
    ir.edges.filter((edge) => edge.label !== undefined).map((edge) => [edge.id, edge.label ?? ""]),
  );
}
