import { describe, expect, it } from "vitest";
import { createTestDiagramStore } from "../test-utils";

/**
 * Regression test for the v10 -> v11 unification bug.
 *
 * Before the unification, `Component.registryServiceId` was written by
 * the custom-component template instancing path and by Canvas.tsx, but
 * `linkComponentToService` (in services.slice.ts) only read `serviceId`.
 * The result was that Components created with a `registryServiceId` set
 * were silently not linked to the Service.
 *
 * After the unification, the legacy field is gone. The link action
 * reads `serviceId` directly; the v10 -> v11 migration (covered by
 * `persist.migrations.test.ts`) copies any pre-v11 `registryServiceId`
 * value into `serviceId` on load. This test exercises the link action
 * end-to-end so a future regression in `linkComponentToService` would
 * fail here.
 */

describe("serviceId unification regression", () => {
  it("linkComponentToService writes to serviceId and the value is readable", () => {
    const store = createTestDiagramStore();

    // Seed a service in the catalog.
    store.getState().addService({
      name: "api",
      description: "Test API",
      repositoryUrl: "",
      technology: ["node"],
    });

    // Seed a diagram and a component on it.
    const diagramId = "diag-1";
    store.setState((state) => {
      state.diagrams[diagramId] = {
        id: diagramId,
        name: "Test",
        description: "",
        level: "context",
        domain: "",
        createdAt: 0,
        updatedAt: 0,
        snapshot: {
          components: {},
          connections: {},
          flows: {},
          iconLibrary: {},
        },
        nodeLayouts: {},
        edgeLayouts: {},
        viewport: { x: 0, y: 0, zoom: 1 },
        folderId: null,
        scenes: {},
        activeSceneId: null,
        compareSceneId: null,
      };
      state.activeDiagramId = diagramId;
      return state;
    });
    const compId = "comp-1";
    // Manually inject the component (skipping addComponent to avoid
    // history/Immer interactions in this unit test).
    store.setState((state) => {
      const d = state.diagrams[diagramId]!;
      d.snapshot.components[compId] = {
        id: compId,
        name: "TestSystem",
        description: "",
        parentId: null,
        type: "system",
      };
      return state;
    });
    expect(store.getState().diagrams[diagramId]?.snapshot.components[compId]).toBeDefined();

    // The service id was generated by addService.
    const svcId = Object.keys(store.getState().serviceCatalog)[0]!;

    // Link them.
    store.getState().linkComponentToService(compId, svcId);

    // The component now carries the serviceId. Read fresh from store
    // because Immer produces a new object reference.
    let comp = store.getState().diagrams[diagramId]!.snapshot.components[compId]!;
    expect(comp.serviceId).toBe(svcId);

    // Unlinking clears it.
    store.getState().linkComponentToService(compId, undefined);
    comp = store.getState().diagrams[diagramId]!.snapshot.components[compId]!;
    expect(comp.serviceId).toBeUndefined();
  });
});
